/*var rec = firebase.database().ref("trainRec/"+date+"/"+kk);
                           if(Clss=="ACount1")
                           {
                                rec.update(
                               {
                                ACount1:inf[kk].ACount1+parseInt(seat),
                               }
                               );
                           }
                           if(Clss=="ACount2")
                           {
                                rec.update(
                               {
                                ACount2:inf[kk].ACount2+parseInt(seat),
                               }
                               );
                           }
                           if(Clss=="GCount")
                           {
                                rec.update(
                               {
                                GCount:inf[kk].GCount+parseInt(seat),
                               }
                               );
                           }*/
