SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


	IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE Name = N'QTY_DIAMETER'
          AND Object_ID = Object_ID(N'CL_JOB_SURFACES_REMOVED_T'))
BEGIN
        ALTER TABLE dbo.CL_JOB_SURFACES_REMOVED_T 
		ADD QTY_DIAMETER decimal(18,2) null DEFAULT 0
END;


		IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE Name = N'ORIGINAL_DIAMETER'
          AND Object_ID = Object_ID(N'CL_JOB_SURFACES_RESTORED_T'))
BEGIN
        ALTER TABLE dbo.CL_JOB_SURFACES_RESTORED_T
		ADD ORIGINAL_DIAMETER decimal(18,2) null DEFAULT 0
END;

	IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE Name = N'RESTORED_DIAMETER'
          AND Object_ID = Object_ID(N'CL_JOB_SURFACES_RESTORED_T'))
BEGIN
        ALTER TABLE dbo.CL_JOB_SURFACES_RESTORED_T
		ADD RESTORED_DIAMETER decimal(18,2) null DEFAULT 0
END;

GO