BEGIN
   IF NOT EXISTS (SELECT TOP 1 * FROM [dbo].[CL_DFR_MASTER_T]
                   WHERE [UNIQUE_KEY] = 'BH DFR')
   BEGIN
   INSERT [dbo].[CL_DFR_MASTER_T] ([DFR_NAME], [ISACTIVE], [UNIQUE_KEY]) VALUES (N'Black Hills DFR', 1, N'BH DFR')
   END
   IF NOT EXISTS (SELECT TOP 1 * FROM [dbo].[CL_DFR_MAPPING_T]
                   WHERE [WI_CONTRACT_ID] in (SELECT TOP 1 WI_CONTRACT_ID FROM [WI_CONTRACT_MASTER_T] where [CONTRACT_NUMBER] = 'BH NE 2019-21')
                   AND [DFR_ID] in (SELECT TOP 1 DFR_ID FROM CL_DFR_MASTER_T WHERE UNIQUE_KEY = 'BH DFR'))
   BEGIN
	INSERT [dbo].[CL_DFR_MAPPING_T] ( [WI_CONTRACT_ID], [DFR_ID], [CREATED_ON], [CREATED_BY], [MODIFIED_ON], [MODIFIED_BY], [ISACTIVE]) VALUES ((SELECT TOP 1 WI_CONTRACT_ID FROM [WI_CONTRACT_MASTER_T] where [CONTRACT_NUMBER] = 'BH NE 2019-21'), (SELECT TOP 1 DFR_ID FROM CL_DFR_MASTER_T WHERE UNIQUE_KEY = 'BH DFR'), NULL, NULL, NULL, NULL, 1)
   END
   IF NOT EXISTS (SELECT TOP 1 * FROM [dbo].[CL_DFR_MAPPING_T]
                   WHERE [WI_CONTRACT_ID] in (SELECT TOP 1 WI_CONTRACT_ID FROM [WI_CONTRACT_MASTER_T] where [CONTRACT_NUMBER] = 'BHNE Central BLNKT 20-23')
                   AND [DFR_ID] in (SELECT TOP 1 DFR_ID FROM CL_DFR_MASTER_T WHERE UNIQUE_KEY = 'BH DFR'))
   BEGIN
	INSERT [dbo].[CL_DFR_MAPPING_T] ( [WI_CONTRACT_ID], [DFR_ID], [CREATED_ON], [CREATED_BY], [MODIFIED_ON], [MODIFIED_BY], [ISACTIVE]) VALUES ((SELECT TOP 1 WI_CONTRACT_ID FROM [WI_CONTRACT_MASTER_T] where [CONTRACT_NUMBER] = 'BHNE Central BLNKT 20-23'), (SELECT TOP 1 DFR_ID FROM CL_DFR_MASTER_T WHERE UNIQUE_KEY = 'BH DFR'), NULL, NULL, NULL, NULL, 1)
   END
    IF NOT EXISTS (SELECT TOP 1 * FROM [dbo].[CL_DFR_MAPPING_T]
                   WHERE [WI_CONTRACT_ID] in (SELECT TOP 1 WI_CONTRACT_ID FROM [WI_CONTRACT_MASTER_T] where [CONTRACT_NUMBER] = 'BHNE Western BLNKT 2020')
                   AND [DFR_ID] in (SELECT TOP 1 DFR_ID FROM CL_DFR_MASTER_T WHERE UNIQUE_KEY = 'BH DFR'))
   BEGIN
	INSERT [dbo].[CL_DFR_MAPPING_T] ( [WI_CONTRACT_ID], [DFR_ID], [CREATED_ON], [CREATED_BY], [MODIFIED_ON], [MODIFIED_BY], [ISACTIVE]) VALUES ((SELECT TOP 1 WI_CONTRACT_ID FROM [WI_CONTRACT_MASTER_T] where [CONTRACT_NUMBER] = 'BHNE Western BLNKT 2020'), (SELECT TOP 1 DFR_ID FROM CL_DFR_MASTER_T WHERE UNIQUE_KEY = 'BH DFR'), NULL, NULL, NULL, NULL, 1)
   END
    IF NOT EXISTS (SELECT TOP 1 * FROM [dbo].[CL_DFR_MAPPING_T]
                   WHERE [WI_CONTRACT_ID] in (SELECT TOP 1 WI_CONTRACT_ID FROM [WI_CONTRACT_MASTER_T] where [CONTRACT_NUMBER] = 'BHNE LINCOLN MTR MOVE 2021')
                   AND [DFR_ID] in (SELECT TOP 1 DFR_ID FROM CL_DFR_MASTER_T WHERE UNIQUE_KEY = 'BH DFR'))
   BEGIN
	INSERT [dbo].[CL_DFR_MAPPING_T] ( [WI_CONTRACT_ID], [DFR_ID], [CREATED_ON], [CREATED_BY], [MODIFIED_ON], [MODIFIED_BY], [ISACTIVE]) VALUES ((SELECT TOP 1 WI_CONTRACT_ID FROM [WI_CONTRACT_MASTER_T] where [CONTRACT_NUMBER] = 'BHNE LINCOLN MTR MOVE 2021'), (SELECT TOP 1 DFR_ID FROM CL_DFR_MASTER_T WHERE UNIQUE_KEY = 'BH DFR'), NULL, NULL, NULL, NULL, 1)
   END
     IF NOT EXISTS (SELECT TOP 1 * FROM [dbo].[CL_DFR_MAPPING_T]
                   WHERE [WI_CONTRACT_ID] in (SELECT TOP 1 WI_CONTRACT_ID FROM [WI_CONTRACT_MASTER_T] where [CONTRACT_NUMBER] = 'BHNE AR METER REPLACEMENT')
                   AND [DFR_ID] in (SELECT TOP 1 DFR_ID FROM CL_DFR_MASTER_T WHERE UNIQUE_KEY = 'BH DFR'))
   BEGIN
	INSERT [dbo].[CL_DFR_MAPPING_T] ( [WI_CONTRACT_ID], [DFR_ID], [CREATED_ON], [CREATED_BY], [MODIFIED_ON], [MODIFIED_BY], [ISACTIVE]) VALUES ((SELECT TOP 1 WI_CONTRACT_ID FROM [WI_CONTRACT_MASTER_T] where [CONTRACT_NUMBER] = 'BHNE AR METER REPLACEMENT'), (SELECT TOP 1 DFR_ID FROM CL_DFR_MASTER_T WHERE UNIQUE_KEY = 'BH DFR'), NULL, NULL, NULL, NULL, 1)
   END
END