SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

	IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE Name = N'IS_JOB_COMPLETED'
          AND Object_ID = Object_ID(N'CL_RESURFACING_T'))
BEGIN
        ALTER TABLE dbo.CL_RESURFACING_T
		ADD  IS_JOB_COMPLETED bit  NULL
END;

	IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE Name = N'RESTORATION_DATA'
          AND Object_ID = Object_ID(N'CL_RESURFACING_T'))
BEGIN
        ALTER TABLE dbo.CL_RESURFACING_T
		ADD  RESTORATION_DATA nvarchar(100)  NULL
END;

	IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE Name = N'IS_RESTORATION_REQUIRED'
          AND Object_ID = Object_ID(N'CL_RESURFACING_T'))
BEGIN
        ALTER TABLE dbo.CL_RESURFACING_T
		ADD  IS_RESTORATION_REQUIRED bit  NULL
END;

GO