/****** Object:  Table [dbo].[CL_T_AND_E_DATA_T]    Script Date: 03-02-2022 20:29:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CL_T_AND_E_DATA_T]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[CL_T_AND_E_DATA_T](
	[T_AND_E_DATA_ID] [int] IDENTITY(1,1) NOT NULL,
	[JOB_ID] [bigint] NOT NULL,
	[PAY_ITEM_DESCRIPTION] [nvarchar](50) NULL,
	[PAY_ITEM_NAME] [nvarchar](50) NULL,
	[JOB_PAY_ITEM_ID] [bigint] NULL,
	[START_TIME] [datetime] NULL,
	[END_TIME] [datetime] NULL,
	[TOTAL_TIME] [nvarchar](20) NULL,
	[IS_COMPLETED] [bit] NULL,
	[CREATED_ON] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFIED_ON] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[IS_ACTIVE] [bit] NULL,
 CONSTRAINT [PK_CL_T_AND_E_DATA_T] PRIMARY KEY CLUSTERED 
(
	[T_AND_E_DATA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_JOB_ID_1]') AND parent_object_id = OBJECT_ID(N'[dbo].[CL_T_AND_E_DATA_T]'))
ALTER TABLE [dbo].[CL_T_AND_E_DATA_T]  WITH CHECK ADD  CONSTRAINT [FK_JOB_ID_1] FOREIGN KEY([JOB_ID])
REFERENCES [dbo].[CL_JOB_T] ([JOB_ID])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_JOB_ID_1]') AND parent_object_id = OBJECT_ID(N'[dbo].[CL_T_AND_E_DATA_T]'))
ALTER TABLE [dbo].[CL_T_AND_E_DATA_T] CHECK CONSTRAINT [FK_JOB_ID_1]
GO
