/****** Object:  Table [dbo].[CL_FAVORITE_CONTRACT_T]    Script Date: 13-05-2022 11:59:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CL_FAVORITE_CONTRACT_T]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[CL_FAVORITE_CONTRACT_T](
	[USER_ID] [int] NOT NULL,
	[WI_COMPANY_ID] [int] NOT NULL,
	[WI_CONTRACT_ID] [int] NOT NULL,
	[CREATED_ON] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFIED_ON] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[ISACTIVE] [bit] NULL,
	[IS_FAVORITE] [bit] NULL,
	[FAVORITE_CONTRACT_ID] [bigint] IDENTITY(1,1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[FAVORITE_CONTRACT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
