/****** Object:  Table [dbo].[CL_PAYITEM_RENTAL_EQUIPMENTS_T]    Script Date: 29-11-2021 14:19:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CL_PAYITEM_RENTAL_EQUIPMENTS_T]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[CL_PAYITEM_RENTAL_EQUIPMENTS_T](
	[PAY_ITEM_RENTAL_EQUIPMENT_ID] [int] IDENTITY(1,1) NOT NULL,
	[JOB_ID] [bigint] NOT NULL,
	[PAY_ITEM_DESCRIPTION] [nvarchar](50) NULL,
	[PAY_ITEM_NAME] [nvarchar](20) NULL,
	[WI_FLEET_ID] [bigint] NULL,
	[EQUIPMENT_DESCRIPTION] [nvarchar](70) NULL,
	[EQUIPMENT_CODE] [nvarchar](10) NULL,
	[STANDARD_HOURS] [decimal](18, 2) NULL,
	[OT_HOURS] [decimal](18, 2) NULL,
	[DT_HOURS] [decimal](18, 2) NULL,
	[IS_ACTIVE] [bit] NULL,
	[CREATED_ON] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFIED_ON] [date] NULL,
	[MODIFIED_BY] [int] NULL,
	[WORK_ORDER] [nvarchar](20) NULL,
 CONSTRAINT [PK_CL_PAYITEM_RENTAL_EQUIPMENTS_T] PRIMARY KEY CLUSTERED 
(
	[PAY_ITEM_RENTAL_EQUIPMENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__CL_PAYITE__JOB_I__1ECF7711]') AND parent_object_id = OBJECT_ID(N'[dbo].[CL_PAYITEM_RENTAL_EQUIPMENTS_T]'))
ALTER TABLE [dbo].[CL_PAYITEM_RENTAL_EQUIPMENTS_T]  WITH CHECK ADD FOREIGN KEY([JOB_ID])
REFERENCES [dbo].[CL_JOB_T] ([JOB_ID])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__CL_PAYITE__WI_FL__1FC39B4A]') AND parent_object_id = OBJECT_ID(N'[dbo].[CL_PAYITEM_RENTAL_EQUIPMENTS_T]'))
ALTER TABLE [dbo].[CL_PAYITEM_RENTAL_EQUIPMENTS_T]  WITH CHECK ADD FOREIGN KEY([WI_FLEET_ID])
REFERENCES [dbo].[WI_FLEET_MASTER_T] ([WI_FLEET_ID])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CL_PAYITEM_RENTAL_EQUIPMENTS_T_CL_PAYITEM_RENTAL_EQUIPMENTS_T]') AND parent_object_id = OBJECT_ID(N'[dbo].[CL_PAYITEM_RENTAL_EQUIPMENTS_T]'))
ALTER TABLE [dbo].[CL_PAYITEM_RENTAL_EQUIPMENTS_T]  WITH CHECK ADD  CONSTRAINT [FK_CL_PAYITEM_RENTAL_EQUIPMENTS_T_CL_PAYITEM_RENTAL_EQUIPMENTS_T] FOREIGN KEY([PAY_ITEM_RENTAL_EQUIPMENT_ID])
REFERENCES [dbo].[CL_PAYITEM_RENTAL_EQUIPMENTS_T] ([PAY_ITEM_RENTAL_EQUIPMENT_ID])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CL_PAYITEM_RENTAL_EQUIPMENTS_T_CL_PAYITEM_RENTAL_EQUIPMENTS_T]') AND parent_object_id = OBJECT_ID(N'[dbo].[CL_PAYITEM_RENTAL_EQUIPMENTS_T]'))
ALTER TABLE [dbo].[CL_PAYITEM_RENTAL_EQUIPMENTS_T] CHECK CONSTRAINT [FK_CL_PAYITEM_RENTAL_EQUIPMENTS_T_CL_PAYITEM_RENTAL_EQUIPMENTS_T]
GO
