BEGIN
   IF NOT EXISTS (SELECT TOP 1 * FROM [dbo].[CL_MATERIAL_TYPE_MASTER_T]
                   WHERE [MATERIAL_TYPE_NAME] = 'Core Hole'
   BEGIN
   INSERT [dbo].[CL_MATERIAL_TYPE_MASTER_T] ([MATERIAL_TYPE_NAME]
      ,[ISACTIVE])
   VALUES ('Core Hole',1)
   END
END