USE [MLink.Development]
GO
/****** Object:  UserDefinedTableType [dbo].[ApproverIdTable]    Script Date: 17-11-2022 15:18:49 ******/
CREATE TYPE [dbo].[ApproverIdTable] AS TABLE(
	[EmployeeNumber] [nvarchar](10) NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[CompanyCodeTable]    Script Date: 17-11-2022 15:18:49 ******/
CREATE TYPE [dbo].[CompanyCodeTable] AS TABLE(
	[Code] [nvarchar](50) NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[CompanyIdTable]    Script Date: 17-11-2022 15:18:49 ******/
CREATE TYPE [dbo].[CompanyIdTable] AS TABLE(
	[CompanyIDS] [int] NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[CONTRACT_CREW_UDT]    Script Date: 17-11-2022 15:18:49 ******/
CREATE TYPE [dbo].[CONTRACT_CREW_UDT] AS TABLE(
	[Foreman_Crew_ID] [bigint] NULL,
	[WI_Employee_ID] [bigint] NULL,
	[Status_Flag] [smallint] NULL,
	[type] [varchar](15) NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[CONTRACT_FLEET_UDT]    Script Date: 17-11-2022 15:18:49 ******/
CREATE TYPE [dbo].[CONTRACT_FLEET_UDT] AS TABLE(
	[Contract_Fleet_ID] [bigint] NULL,
	[WI_Fleet_ID] [bigint] NULL,
	[Status_Flag] [smallint] NULL,
	[type] [varchar](15) NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[ContractList]    Script Date: 17-11-2022 15:18:49 ******/
CREATE TYPE [dbo].[ContractList] AS TABLE(
	[ID] [int] NULL,
	[Contract] [nvarchar](100) NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[FAVORITE_PAYITEM_UDT]    Script Date: 17-11-2022 15:18:49 ******/
CREATE TYPE [dbo].[FAVORITE_PAYITEM_UDT] AS TABLE(
	[Favorite_Payitem_ID] [bigint] NULL,
	[WI_Payitem_ID] [bigint] NULL,
	[Status_Flag] [tinyint] NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[FLEET_WEEKEND_MILES_UDT]    Script Date: 17-11-2022 15:18:49 ******/
CREATE TYPE [dbo].[FLEET_WEEKEND_MILES_UDT] AS TABLE(
	[Contract_Fleet_ID] [bigint] NOT NULL,
	[Weekend_Miles] [decimal](18, 2) NOT NULL,
	[Status_Flag] [smallint] NOT NULL,
	[Comments] [nvarchar](1000) NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[FOREMAN_JOB_LIST_UDT]    Script Date: 17-11-2022 15:18:49 ******/
CREATE TYPE [dbo].[FOREMAN_JOB_LIST_UDT] AS TABLE(
	[JOB_ID] [bigint] NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[FOREMAN_JOBS_UDT]    Script Date: 17-11-2022 15:18:49 ******/
CREATE TYPE [dbo].[FOREMAN_JOBS_UDT] AS TABLE(
	[JOB_NUMBER] [varchar](10) NULL,
	[JOB_ID] [bigint] NULL,
	[JOB_DATE] [datetime] NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[FOREMAN_JOBS_UDT_TEST]    Script Date: 17-11-2022 15:18:49 ******/
CREATE TYPE [dbo].[FOREMAN_JOBS_UDT_TEST] AS TABLE(
	[JOB_ID] [int] NULL,
	[JOB_NUMBER] [varchar](50) NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[ForemanUserIdTable]    Script Date: 17-11-2022 15:18:49 ******/
CREATE TYPE [dbo].[ForemanUserIdTable] AS TABLE(
	[UserId] [int] NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[HDD_CONTRACT_LIST_UDT]    Script Date: 17-11-2022 15:18:49 ******/
CREATE TYPE [dbo].[HDD_CONTRACT_LIST_UDT] AS TABLE(
	[CONTRACT_NUMBER] [nvarchar](100) NOT NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[INTLIST_UDT]    Script Date: 17-11-2022 15:18:49 ******/
CREATE TYPE [dbo].[INTLIST_UDT] AS TABLE(
	[Value] [bigint] NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[JOB_COMMENT_UDT]    Script Date: 17-11-2022 15:18:49 ******/
CREATE TYPE [dbo].[JOB_COMMENT_UDT] AS TABLE(
	[Job_ID] [bigint] NULL,
	[Comment_Desc] [nvarchar](4000) NULL,
	[Status_Flag] [smallint] NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[JOB_EQUIPMENT_UDT]    Script Date: 17-11-2022 15:18:49 ******/
CREATE TYPE [dbo].[JOB_EQUIPMENT_UDT] AS TABLE(
	[Job_Equipment_ID] [bigint] NOT NULL,
	[Job_ID] [bigint] NOT NULL,
	[Contract_Fleet_ID] [bigint] NOT NULL,
	[WBS_Code] [nvarchar](50) NOT NULL,
	[Hours] [decimal](18, 2) NOT NULL,
	[Equipment_Charge] [money] NULL,
	[Transfer_To_Company] [decimal](18, 2) NULL,
	[Serviced] [tinyint] NULL,
	[Last_Serviced_Date] [datetime] NULL,
	[Status_Flag] [smallint] NULL,
	[Active_Flag] [bit] NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[JOB_LABOR_UDT]    Script Date: 17-11-2022 15:18:49 ******/
CREATE TYPE [dbo].[JOB_LABOR_UDT] AS TABLE(
	[Job_Labor_ID] [bigint] NOT NULL,
	[Job_ID] [bigint] NOT NULL,
	[Foreman_Crew_ID] [bigint] NOT NULL,
	[WBS_Code] [nvarchar](50) NOT NULL,
	[WBS_Description] [nvarchar](500) NULL,
	[Standard_Hours] [decimal](18, 2) NOT NULL,
	[OT_Hours] [decimal](18, 2) NOT NULL,
	[DT_Hours] [decimal](18, 2) NOT NULL,
	[Overrides] [money] NULL,
	[Paid_Time_Off] [decimal](18, 2) NULL,
	[Holiday_Pay] [money] NULL,
	[Auto_Allowance] [money] NULL,
	[Per_Diem] [money] NULL,
	[Per_Diem_Type] [varchar](5) NULL,
	[Sick_Leave_Type] [varchar](10) NULL,
	[Rig_Rentals] [money] NULL,
	[Misc_Code] [money] NULL,
	[Travel_Pay] [money] NULL,
	[Wait_Time_Hours] [decimal](18, 2) NOT NULL,
	[Pay_Level] [tinyint] NULL,
	[Union_Code] [varchar](50) NULL,
	[WI_City_ID] [smallint] NOT NULL,
	[Status_Flag] [smallint] NOT NULL,
	[Active_Flag] [bit] NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[JOB_PAYITEM_LIST_UDT]    Script Date: 17-11-2022 15:18:49 ******/
CREATE TYPE [dbo].[JOB_PAYITEM_LIST_UDT] AS TABLE(
	[WI_Payitem_ID] [bigint] NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[JOB_PAYITEM_UDT]    Script Date: 17-11-2022 15:18:49 ******/
CREATE TYPE [dbo].[JOB_PAYITEM_UDT] AS TABLE(
	[Job_Payitem_ID] [bigint] NULL,
	[SNo] [int] NULL,
	[Job_ID] [bigint] NULL,
	[WI_Payitem_ID] [bigint] NULL,
	[QTY] [numeric](12, 2) NULL,
	[Street_Address] [nvarchar](30) NULL,
	[PO_Number] [nvarchar](50) NULL,
	[Work_Order] [nvarchar](50) NULL,
	[WI_Customer_ID] [int] NULL,
	[WI_City_ID] [smallint] NULL,
	[Status_Flag] [smallint] NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[NotificationIdTable]    Script Date: 17-11-2022 15:18:49 ******/
CREATE TYPE [dbo].[NotificationIdTable] AS TABLE(
	[NotificationId] [int] NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[SUPERINTENDENT_REVIEWER_UDT]    Script Date: 17-11-2022 15:18:49 ******/
CREATE TYPE [dbo].[SUPERINTENDENT_REVIEWER_UDT] AS TABLE(
	[Superintendent_Reviewer_ID] [bigint] NULL,
	[reviewer_ID] [bigint] NULL,
	[reviewer_Code] [varchar](50) NULL,
	[reviewer_Name] [varchar](50) NULL,
	[Status_Flag] [smallint] NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[UserIdTable]    Script Date: 17-11-2022 15:18:49 ******/
CREATE TYPE [dbo].[UserIdTable] AS TABLE(
	[UserId] [int] NULL
)
GO
/****** Object:  UserDefinedTableType [dbo].[WiSuperintendentIdTable]    Script Date: 17-11-2022 15:18:49 ******/
CREATE TYPE [dbo].[WiSuperintendentIdTable] AS TABLE(
	[WiSuperintendentId] [bigint] NULL
)
GO
/****** Object:  UserDefinedFunction [dbo].[GET_USER_WEEKEND_MILES_FN]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE FUNCTION [dbo].[GET_USER_WEEKEND_MILES_FN] (@FleetID BIGINT, @UserID INT)
RETURNS DECIMAL(18,2)
AS
BEGIN

	RETURN (SELECT MAX(ISNULL(WEEKEND_MILES, 0)) 
	FROM GET_CONTRACT_FLEET_V 
	WHERE WI_Fleet_ID = @FleetID AND [User_ID] = @UserID
	 AND ISNULL([ISACTIVE], 1) = 1)

END;

GO
/****** Object:  UserDefinedFunction [dbo].[GET_WEEKEND_MILES_FN]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE FUNCTION [dbo].[GET_WEEKEND_MILES_FN] (@FleetID BIGINT, @ContractID INT)
RETURNS DECIMAL(18,2)
AS
BEGIN

	RETURN (SELECT MAX(ISNULL(WEEKEND_MILES, 0)) 
	FROM GET_CONTRACT_FLEET_V 
	WHERE WI_Fleet_ID = @FleetID --AND WI_Contract_ID = @ContractID
	)

END;
GO
/****** Object:  UserDefinedFunction [dbo].[Split]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
Create FUNCTION [dbo].[Split](@String varchar(8000), @Delimiter char(1))     
returns @temptable TABLE (items varchar(8000))     
as     
begin     
	declare @idx int     
	declare @slice varchar(8000)     
    
	select @idx = 1     
		if len(@String)<1 or @String is null  return     
    
	while @idx!= 0     
	begin     
		set @idx = charindex(@Delimiter,@String)     
		if @idx!=0     
			set @slice = left(@String,@idx - 1)     
		else     
			set @slice = @String     
		
		if(len(@slice)>0)
			insert into @temptable(Items) values(@slice)     

		set @String = right(@String,len(@String) - @idx)     
		if len(@String) = 0 break     
	end 
return     
end
GO
/****** Object:  View [dbo].[GET_WI_EMPLOYEE_MASTER_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[GET_WI_EMPLOYEE_MASTER_V]
AS
SELECT WI_EMPLOYEE_ID, LTRIM(RTRIM(EMPLOYEE_ID)) AS EMPLOYEE_ID, EMPLOYEE_NAME, TYPE, PROJECT, EMAIL_ADDRESS, CLASSIFICATION, TERMINATION_DATE, 
                  LTRIM(RTRIM(COMPANY_CODE)) AS COMPANY_CODE, ALPHASORT, ADDRESS, CITY_ID, STATE, ZIP, DEPARTMENT_CODE, STREET_ADDRESS, STATUS, 
                  EFFECTIVE_DATE, PAY_RATE_CODE, UNION_CODE, PAY_TYPE, CREATE_DATE, LAST_UPDATE, CREATED, DELETED, CREATED_BY, DELETED_BY, TITLE
FROM     dbo.WI_EMPLOYEE_MASTER_T
WHERE  (TERMINATION_DATE IS NULL) AND (STATUS = 'A')
GO
/****** Object:  View [dbo].[GET_CONTRACT_CREW_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[GET_CONTRACT_CREW_V]
AS
	SELECT	FOREMAN_CREW_ID, CM.WI_EMPLOYEE_ID,  LTRIM(RTRIM(EM.EMPLOYEE_ID)) AS EMPLOYEE_ID, 
			LTRIM(RTRIM(EM.EMPLOYEE_NAME)) AS EMPLOYEE_NAME, [USER_ID], WI_CONTRACT_ID,
			LTRIM(RTRIM(EM.EMPLOYEE_NAME)) + ' - ' + LTRIM(RTRIM(EM.EMPLOYEE_ID)) AS EMPLOYEE_INFO, 
			LTRIM(RTRIM(EM.UNION_CODE)) AS UNION_CODE,
			ISFOREMAN, CM.[ISACTIVE]
	FROM	CL_CONTRACT_CREW_T CM
	INNER JOIN GET_WI_EMPLOYEE_MASTER_V EM ON EM.WI_EMPLOYEE_ID = CM.WI_EMPLOYEE_ID 
	--WHERE ISNULL(CM.[ISACTIVE], 1) = 1



GO
/****** Object:  View [dbo].[GET_USERS_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[GET_USERS_V]
AS
SELECT		U.[USER_ID], U.WI_EMPLOYEE_ID, U.USER_ROLE_ID, U.LAST_LOGIN,
			EM.EMPLOYEE_ID, EM.EMPLOYEE_NAME, EM.[TYPE], EM.TITLE
FROM		CL_USER U
INNER JOIN	GET_WI_EMPLOYEE_MASTER_V EM ON EM.WI_EMPLOYEE_ID = U.WI_EMPLOYEE_ID 
GO
/****** Object:  View [dbo].[GET_WI_JOB_INFO_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[GET_WI_JOB_INFO_V]
AS 

	SELECT	DISTINCT WI_JOB_ID, LTRIM(RTRIM(JOB_NUMBER)) AS JOB_NUMBER, JOB_DESCRIPTION, JM.COMPANY_CODE, JM.CUSTOMER_CODE, 
			CONTRACT_NUMBER, SUPERINTENDENT, JM.[STATUS], ADDRESS_1, ADDRESS_2, 
			CITY, JM.[STATE], ZIP_CODE, PHONER, [SOURCE], JM.CREATED, JM.CREATE_DATE, EM.EMPLOYEE_NAME, EM.EMPLOYEE_ID, CLU.WI_EMPLOYEE_ID, CLU.[USER_ID]
	FROM	WI_JOB_MASTER_T JM
	INNER JOIN GET_WI_EMPLOYEE_MASTER_V EM ON EM.EMPLOYEE_ID = LTRIM(RTRIM(JM.SUPERINTENDENT))
	INNER JOIN GET_USERS_V CLU ON CLU.WI_EMPLOYEE_ID = EM.WI_EMPLOYEE_ID

GO
/****** Object:  View [dbo].[GET_JOB_STATUS_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [dbo].[GET_JOB_STATUS_V]
AS
	SELECT JOB_STATUS_ID AS Job_Status_ID , JOB_STATUS_NAME AS Job_Status
	FROM CL_JOB_STATUS_T WHERE ISACTIVE = 1



GO
/****** Object:  View [dbo].[GET_WI_EMPLOYEE_MASTER_STATUS_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[GET_WI_EMPLOYEE_MASTER_STATUS_V]
AS
  SELECT WI_EMPLOYEE_ID, LTRIM(RTRIM(EMPLOYEE_ID)) AS EMPLOYEE_ID, EMPLOYEE_NAME, TYPE, PROJECT, EMAIL_ADDRESS, CLASSIFICATION,
    TERMINATION_DATE, LTRIM(RTRIM(COMPANY_CODE)) AS COMPANY_CODE,
    ALPHASORT, ADDRESS, CITY_ID, STATE, ZIP, DEPARTMENT_CODE, STREET_ADDRESS, STATUS, EFFECTIVE_DATE, PAY_RATE_CODE,
    UNION_CODE, PAY_TYPE, CREATE_DATE, LAST_UPDATE, CREATED, DELETED, CREATED_BY, DELETED_BY, TITLE
  FROM WI_EMPLOYEE_MASTER_T


GO
/****** Object:  View [dbo].[GET_SUPERINTENDENT_JOBS_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*Alter [GET_SUPERINTENDENT_JOBS_V] to call the newly created view*/
CREATE VIEW [dbo].[GET_SUPERINTENDENT_JOBS_V]
AS
  SELECT JT.JOB_ID, JT.WI_JOB_ID, JM.JOB_NUMBER, JT.JOB_START_DATE, JT.JOB_STATUS_ID, SM.JOB_STATUS,
    JT.[USER_ID] AS CL_FOREMAN_ID, UT.WI_EMPLOYEE_ID AS WI_FOREMAN_ID, EM.EMPLOYEE_ID AS FOREMAN_CODE, EM.EMPLOYEE_NAME AS FOREMAN_NAME,
    JM.WI_EMPLOYEE_ID AS WI_SUPERINTENDENT_ID, LTRIM(RTRIM(JM.SUPERINTENDENT)) AS SUPERINTENDENT_CODE, JM.EMPLOYEE_NAME AS SUPERINTENDENT_NAME
			, JM.[CONTRACT_NUMBER]
  FROM CL_JOB_T AS JT
    JOIN CL_USER	 AS UT ON JT.[USER_ID] = UT.[USER_ID]
    JOIN GET_WI_EMPLOYEE_MASTER_STATUS_V AS EM ON EM.WI_EMPLOYEE_ID = UT.WI_EMPLOYEE_ID
    JOIN GET_WI_JOB_INFO_V AS JM ON JT.WI_JOB_ID = JM.WI_JOB_ID
    JOIN GET_JOB_STATUS_V AS SM ON SM.JOB_STATUS_ID = JT.JOB_STATUS_ID
  --JOIN	GET_WI_EMPLOYEE_MASTER_V AS EM1 ON EM1.EMPLOYEE_ID = LTRIM(RTRIM(JM.SUPERINTENDENT))
  WHERE   JM.[STATUS] = 'A'


GO
/****** Object:  View [dbo].[GET_WI_COMPANY_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[GET_WI_COMPANY_V]
AS 

	SELECT WI_COMPANY_ID, LTRIM(RTRIM(COMPANY_CODE)) AS COMPANY_CODE, COMPANY_NAME  
	FROM   WI_COMPANY_MASTER_T 
	WHERE  ISNULL(STATUS, 'A') = 'A';



GO
/****** Object:  View [dbo].[GET_WI_CONTRACT_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[GET_WI_CONTRACT_V]
AS
SELECT        WI_CONTRACT_ID, LTRIM(RTRIM(CONTRACT_NUMBER)) AS CONTRACT_NUMBER, WI_CUSTOMER_ID, WI_COMPANY_ID, STATUS, IS_SPECIAL_PROJECT
FROM            dbo.WI_CONTRACT_MASTER_T
WHERE        (ISNULL(STATUS, N'A') = 'A')
GO
/****** Object:  View [dbo].[GET_WI_CUSTOMER_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[GET_WI_CUSTOMER_V]
AS
SELECT WI_CUSTOMER_ID, WI_COMPANY_ID, LTRIM(RTRIM(CUSTOMER_CODE)) AS CUSTOMER_CODE, NAME, TYPE, STATUS, WI_CONTRACT_ID
FROM     dbo.WI_CUSTOMER_MASTER_T
WHERE  (ISNULL(STATUS, N'A') = 'A') AND (DELETED < 0)
GO
/****** Object:  View [dbo].[GET_SUPERINTENDENT_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [dbo].[GET_SUPERINTENDENT_V] 
AS
	SELECT		DISTINCT JM.WI_JOB_ID, EM.EMPLOYEE_ID, EM.EMPLOYEE_NAME, JM.COMPANY_CODE, CM.WI_COMPANY_ID, JM.CUSTOMER_CODE, CUM.WI_CUSTOMER_ID,
				JM.CONTRACT_NUMBER, COM.WI_CONTRACT_ID, EM.[STATUS], EM.WI_EMPLOYEE_ID
	FROM		WI_JOB_MASTER_T AS JM 
	JOIN		GET_WI_EMPLOYEE_MASTER_V AS EM ON EM.EMPLOYEE_ID = LTRIM(RTRIM(JM.SUPERINTENDENT))
	JOIN		CL_USER U ON U.WI_EMPLOYEE_ID = EM.WI_EMPLOYEE_ID
	LEFT JOIN	GET_WI_COMPANY_V	AS CM	ON CM.COMPANY_CODE = LTRIM(RTRIM(JM.COMPANY_CODE))
	LEFT JOIN	GET_WI_CUSTOMER_V	AS CUM	ON CUM.CUSTOMER_CODE = LTRIM(RTRIM(JM.CUSTOMER_CODE))
	LEFT JOIN	GET_WI_CONTRACT_V	AS COM	ON COM.CONTRACT_NUMBER = LTRIM(RTRIM(JM.CONTRACT_NUMBER))




GO
/****** Object:  View [dbo].[GET_CL_JOB_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[GET_CL_JOB_V]
AS 

	SELECT	JT.[JOB_ID], JT.WI_JOB_ID, JT.[JOB_START_DATE], JT.[JOB_STATUS_ID], JS.JOB_STATUS_NAME,
			JT.[USER_ID], U.[USER_NAME], U.USER_TYPE, JT.SUPERINTENDENT_COMMENT, JT.[STATUS],
			JT.CREATED_ON, JT.CREATED_BY, JT.MODIFIED_ON, JT.MODIFIED_BY, WJM.JOB_NUMBER
	FROM	CL_JOB_T		AS JT
	JOIN	CL_JOB_STATUS_T	AS JS ON JS.JOB_STATUS_ID = JT.JOB_STATUS_ID
	JOIN	CL_USER			AS U ON U.[USER_ID] = JT.[USER_ID]
	JOIN	WI_JOB_MASTER_T	AS WJM ON WJM.WI_JOB_ID = JT.WI_JOB_ID



GO
/****** Object:  View [dbo].[GET_WI_JOB_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[GET_WI_JOB_V]
AS 

	SELECT	WI_JOB_ID, LTRIM(RTRIM(JOB_NUMBER)) AS JOB_NUMBER, JOB_DESCRIPTION, LTRIM(RTRIM(COMPANY_CODE)) AS COMPANY_CODE, 
			LTRIM(RTRIM(CUSTOMER_CODE)) AS CUSTOMER_CODE, 
			LTRIM(RTRIM(CONTRACT_NUMBER)) AS CONTRACT_NUMBER, LTRIM(RTRIM(SUPERINTENDENT)) AS SUPERINTENDENT, [STATUS], ADDRESS_1, ADDRESS_2, 
			CITY, [STATE], ZIP_CODE, PHONER, [SOURCE], CREATED, CREATE_DATE
	FROM	WI_JOB_MASTER_T


GO
/****** Object:  View [dbo].[GET_ASSIGNED_JOB_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[GET_ASSIGNED_JOB_V]
AS 
	SELECT	CLJV.[JOB_ID], CLJV.WI_JOB_ID, CLJV.[JOB_START_DATE], CLJV.[JOB_STATUS_ID], CLJV.JOB_STATUS_NAME,
			CLJV.[USER_ID], CLJV.[USER_NAME], CLJV.USER_TYPE, CLJV.SUPERINTENDENT_COMMENT, CLJV.[STATUS],
			WIJV.JOB_NUMBER, WIJV.JOB_DESCRIPTION
	FROM	GET_CL_JOB_V AS CLJV
	JOIN	GET_WI_JOB_V AS WIJV ON CLJV.WI_JOB_ID = WIJV.WI_JOB_ID 
	--SELECT	JT.JOB_ID, JT.WI_JOB_ID, JM.JOB_NUMBER, JT.JOB_START_DATE,  JT.JOB_STATUS_ID, SM.JOB_STATUS,
	--		JT.[USER_ID] AS FOREMAN_ID, UT.[USER_NAME], UT.WI_EMPLOYEE_ID, EM.EMPLOYEE_ID, EM.EMPLOYEE_NAME,
	--		LTRIM(RTRIM(JM.SUPERINTENDENT)) AS SUPERINTENDENT, EM1.WI_EMPLOYEE_ID AS SUPERINTENDENT_ID
	--FROM	CL_JOB_T AS JT
	--JOIN	CL_USER	 AS UT ON JT.USER_ID = UT.USER_ID 
	--JOIN	GET_WI_EMPLOYEE_MASTER_V AS EM ON EM.WI_EMPLOYEE_ID = UT.WI_EMPLOYEE_ID 
	--JOIN	WI_JOB_MASTER_T AS JM ON JT.WI_JOB_ID = JM.WI_JOB_ID 
	--JOIN	GET_JOB_STATUS_V AS SM ON SM.JOB_STATUS_ID = JT.JOB_STATUS_ID 
	--JOIN	GET_WI_EMPLOYEE_MASTER_V AS EM1 ON EM1.EMPLOYEE_ID = LTRIM(RTRIM(JM.SUPERINTENDENT))
	--WHERE   JM.[STATUS] = 'A'

GO
/****** Object:  View [dbo].[GET_PAYITEMS_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[GET_PAYITEMS_V] 
AS

	SELECT	DISTINCT PIM.WI_PAYITEM_ID AS WI_Payitem_ID,  PIM.COMPANY_CODE AS Company_Code, PIM.CONTRACT_NUMBER AS Contract_Number,
			PIM.TIER1_CODE AS Tier1_Code, PIM.TIER1_DESCRIPTION AS Tier1_Description, PIM.TIER2_CODE AS Tier2_Code, 
			PIM.TIER2_DESCRIPTION AS Tier2_Description, PIM.TIER3_CODE AS Tier3_Code, PIM.TIER3_DESCRIPTION AS Tier3_Description,
			PIM.PHASE_CODE AS Phase_Code, PIM.UOM AS UOM, PIM.PAYITEM AS Payitem, PIM.[DESCRIPTION] AS Payitem_Description,
			PIM. WBS_CODE AS WBS_Code, WBS_DESCRIPTION AS WBS_Description, PIM.[STATUS] AS PayitemStatus, 
			CM.WI_COMPANY_ID AS WI_Company_ID, COM.WI_CONTRACT_ID AS WI_Contract_ID, COM.WI_CUSTOMER_ID AS WI_Customer_ID
	FROM	WI_PAYITEM_MASTER_T PIM
	INNER JOIN GET_WI_COMPANY_V  CM ON CM.COMPANY_CODE = LTRIM(RTRIM(PIM.COMPANY_CODE)) 
	INNER JOIN GET_WI_CONTRACT_V COM ON COM.CONTRACT_NUMBER = LTRIM(RTRIM(PIM.CONTRACT_NUMBER))
	WHERE	ISNULL(PIM.STATUS,1) = 1



GO
/****** Object:  View [dbo].[GET_UNASSIGNED_JOB_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[GET_UNASSIGNED_JOB_V]
AS 
		SELECT JM.WI_Job_ID, JM.Job_Description, JM.Company_Code, JM.Customer_Code, JM.CONTRACT_NUMBER as Contract_Number,
		JM.Superintendent, JM.Status, JM.Address_1, JM.Address_2, JM.City, JM.State, JM.Zip_code, JM.Phoner, JM.Job_Number,
		CM.WI_Contract_ID, EM.WI_EMPLOYEE_ID as WI_Employee_ID, COM.WI_COMPANY_ID as WI_Company_ID
		FROM [WI_JOB_MASTER_T] JM
		INNER JOIN [GET_WI_COMPANY_V] COM ON COM.COMPANY_CODE = LTRIM(RTRIM(JM.COMPANY_CODE)) 
		INNER JOIN [GET_WI_CONTRACT_V] CM ON CM.CONTRACT_NUMBER = LTRIM(RTRIM(JM.CONTRACT_NUMBER)) 
		INNER JOIN [GET_WI_EMPLOYEE_MASTER_V] EM ON EM.EMPLOYEE_ID = LTRIM(RTRIM(JM.SUPERINTENDENT))
		WHERE ISNULL(JM.[STATUS],'A') = 'A'

		--SELECT JM.WI_Job_ID, JM.Job_Description, JM.Company_Code, JM.Customer_Code, JM.CONTRACT_NUMBER as Contract_Number,
		--JM.Superintendent, JM.Status, JM.Address_1, JM.Address_2, JM.City, JM.State, JM.Zip_code, JM.Phoner, JM.Job_Number,
		--CM.WI_Contract_ID, EM.WI_EMPLOYEE_ID as WI_Employee_ID
		--FROM [WI_JOB_MASTER_T] JM
		--LEFT JOIN [GET_WI_CONTRACT_V] CM ON CM.CONTRACT_NUMBER = LTRIM(RTRIM(JM.CONTRACT_NUMBER)) 
		--LEFT JOIN [GET_WI_EMPLOYEE_MASTER_V] EM ON EM.EMPLOYEE_ID = LTRIM(RTRIM(JM.SUPERINTENDENT))-- AND EM.[STATUS] = 'A'
		--WHERE ISNULL(JM.[STATUS],'A') = 'A' --OR ISNULL(JM.[STATUS],'N') = 'N'

GO
/****** Object:  View [dbo].[vw_CL_Missing_Timesheet]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vw_CL_Missing_Timesheet] AS
	
	With Dates as ( 
		Select 
			 cast(DATEADD(wk,DATEDIFF(wk,7,getdate()),-1) as date) CurrentStartDate
			, cast(DATEADD(wk,DATEDIFF(wk,7,getdate()),5) as date) CurrentEndDate
			, cast(dateadd(DAY,-7,DATEADD(wk,DATEDIFF(wk,7,getdate()),-1)) as date) PrevWeek
			, cast(dateadd(DAY,-1,DATEADD(wk,DATEDIFF(wk,7,getdate()),-1)) as date) PrevDay
	)
	, CurrentWeek as (
		SELECT DISTINCT 
			emp.EMPLOYEE_ID
		FROM		  
			dbo.CL_JOB_T JOB 
				INNER JOIN 
			dbo.CL_JOB_LABOR_T LABOR ON labor.JOB_ID = JOB.JOB_ID
					and LABOR.STANDARD_HOURS > 0 and labor.ISACTIVE = 1 
				INNER JOIN
			dbo.CL_JOB_STATUS_T L1 on JOB.JOB_STATUS_ID = L1.JOB_STATUS_ID 
					and L1.JOB_STATUS_NAME in ('approved') 
				INNER JOIN
			dbo.GET_CONTRACT_CREW_V CREW on LABOR.FOREMAN_CREW_ID = CREW.FOREMAN_CREW_ID
				INNER JOIN
			WI_EMPLOYEE_MASTER_T AS Emp ON  CREW.WI_EMPLOYEE_ID = Emp.WI_EMPLOYEE_ID 
				INNER JOIN 
			CL_USER usr on usr.USER_ID = crew.USER_ID
				INNER JOIN
			WI_EMPLOYEE_MASTER_T AS Emp1 ON  usr.WI_EMPLOYEE_ID = Emp1.WI_EMPLOYEE_ID 
				INNER JOIN 
			WI_JOB_MASTER_T WIJOB on JOB.WI_JOB_ID = WIJOB.WI_JOB_ID
				INNER JOIN
			WI_EMPLOYEE_MASTER_T AS Emp2 ON  WIJOB.SUPERINTENDENT = Emp2.EMPLOYEE_ID 
				JOIN Dates D on
					JOB.JOB_START_DATE >= CurrentStartDate
					and JOB.JOB_START_DATE <= CurrentEndDate  
	)
	, PreviousWeek as(
 
		SELECT DISTINCT 
			Emp.EMPLOYEE_ID
			,Emp.EMPLOYEE_NAME
			,Emp.COMPANY_CODE
			,Emp2.EMPLOYEE_NAME SUPERINTENDENT
			,WIJOB.JOB_NUMBER
			,Emp1.EMPLOYEE_NAME FOREMAN
			,WIJOB.CONTRACT_NUMBER
		FROM  dbo.CL_JOB_T JOB 
				INNER JOIN 
			dbo.CL_JOB_LABOR_T LABOR ON labor.JOB_ID = JOB.JOB_ID
					and LABOR.STANDARD_HOURS > 0 and labor.ISACTIVE = 1 
				INNER JOIN
			dbo.CL_JOB_STATUS_T L1 on JOB.JOB_STATUS_ID = L1.JOB_STATUS_ID 
					and L1.JOB_STATUS_NAME in ('approved') 
				INNER JOIN
			dbo.GET_CONTRACT_CREW_V CREW on LABOR.FOREMAN_CREW_ID = CREW.FOREMAN_CREW_ID
				INNER JOIN
			WI_EMPLOYEE_MASTER_T AS Emp ON  CREW.WI_EMPLOYEE_ID = Emp.WI_EMPLOYEE_ID 
				INNER JOIN 
			CL_USER usr on usr.USER_ID = crew.USER_ID
				INNER JOIN
			WI_EMPLOYEE_MASTER_T AS Emp1 ON  usr.WI_EMPLOYEE_ID = Emp1.WI_EMPLOYEE_ID 
				INNER JOIN 
			WI_JOB_MASTER_T WIJOB on JOB.WI_JOB_ID = WIJOB.WI_JOB_ID
				INNER JOIN
			WI_EMPLOYEE_MASTER_T AS Emp2 ON  WIJOB.SUPERINTENDENT = Emp2.EMPLOYEE_ID 

		JOIN Dates D on
			JOB.JOB_START_DATE >= PrevWeek 
			and JOB.JOB_START_DATE<= PrevDay
	)

	SELECT DISTINCT 
		a.EMPLOYEE_ID 
		,a.EMPLOYEE_NAME
		,a.COMPANY_CODE
		,a.SUPERINTENDENT
		,a.JOB_NUMBER
		,a.FOREMAN
		,a.CONTRACT_NUMBER
	FROM PreviousWeek a
	Where
		a.EMPLOYEE_ID not in
			(
				Select 
					EMPLOYEE_ID
				From CurrentWeek
			)

GO
/****** Object:  View [dbo].[GET_CONTRACT_CREW_STATUS_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[GET_CONTRACT_CREW_STATUS_V]
AS
  SELECT FOREMAN_CREW_ID, CM.WI_EMPLOYEE_ID, LTRIM(RTRIM(EM.EMPLOYEE_ID)) AS EMPLOYEE_ID,
    LTRIM(RTRIM(EM.EMPLOYEE_NAME)) AS EMPLOYEE_NAME, [USER_ID], WI_CONTRACT_ID,
    LTRIM(RTRIM(EM.EMPLOYEE_NAME)) + ' - ' + LTRIM(RTRIM(EM.EMPLOYEE_ID)) AS EMPLOYEE_INFO,
    LTRIM(RTRIM(EM.UNION_CODE)) AS UNION_CODE,
    ISFOREMAN, CM.[ISACTIVE]
  FROM CL_CONTRACT_CREW_T CM
    INNER JOIN GET_WI_EMPLOYEE_MASTER_STATUS_V EM ON EM.WI_EMPLOYEE_ID = CM.WI_EMPLOYEE_ID


GO
/****** Object:  View [dbo].[GET_JOB_LABORS_STATUS_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[GET_JOB_LABORS_STATUS_V]
AS
  SELECT JL.JOB_LABOR_ID, JL.JOB_ID, JL.FOREMAN_CREW_ID, CC.EMPLOYEE_INFO, CC.EMPLOYEE_ID, CC.EMPLOYEE_NAME, JL.WI_PAYITEM_ID, JL.WBS_Code, JL.WBS_DESCRIPTION, JL.STANDARD_HOURS,
    JL.OT_HOURS, JL.DT_HOURS, JL.PER_DIEM, JL.RIG_RENTALS, JL.PAY_LEVEL, JL.UNION_CODE, JL.WI_CITY_ID, CM.CITY_CODE, C.COMMENT_ID, C.COMMENT_DESC, CC.WI_CONTRACT_ID,
    JL.PAID_TIME_OFF, JL.HOLIDAY_PAY, JL.AUTO_ALLOWANCE, JL.OVERRIDES, ISNULL(CC.ISACTIVE,1) AS IsActive, ISNULL(JL.ISACTIVE, 1) AS Job_Labor_Status
  FROM dbo.CL_JOB_LABOR_T AS JL
    INNER JOIN dbo.GET_CONTRACT_CREW_STATUS_V AS CC ON CC.FOREMAN_CREW_ID = JL.FOREMAN_CREW_ID
    INNER JOIN dbo.WI_CITYCODE_MASTER_T AS CM ON CM.WI_CITY_ID = JL.WI_CITY_ID
    LEFT OUTER JOIN dbo.CL_COMMENT_T AS C ON C.JOB_ID = JL.JOB_ID AND C.COMMENT_TYPE = 'L'


GO
/****** Object:  View [dbo].[vw_Equipment_Master]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

 CREATE VIEW [dbo].[vw_Equipment_Master] AS
 SELECT A.*, B.Status_Description as EquipStatus, B.Status_Type as [ActiveRetired], C.Equipment_Type_Description EquipType  
 FROM [SIGMA].[WEBIMPORT].[dbo].[EC_EQUIPMENT_MASTER_MC] A
 INNER JOIN [SIGMA].[WEBIMPORT].[dbo].[EC_EQUIPMENT_STATUS_MC] B ON A.Equipment_Status = B.Equipment_Status
 INNER JOIN [SIGMA].[WEBIMPORT].[dbo].[EC_EQUIPMENT_TYPE_MC] C ON A.Equipment_Type = C.Equipment_Type
 WHERE A.Company_Code IN ('555') AND B.Company_Code IN ('555') AND  C.Company_Code IN ('555')



GO
/****** Object:  View [dbo].[vw_Weekend_Mile_Status]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


Create VIEW [dbo].[vw_Weekend_Mile_Status] AS


SELECT G.CONTRACT_NUMBER,E.WI_CONTRACT_ID,F.EQUIPMENT_DESCRIPTION, F.Last_Meter,F.EQUIPMENT_CODE,f.EQUIPMENT_STATUS,F.EQUIPMENT_TYPE,F.METER_TYPE,F.LICENSE_NUMBER,F.DIVISION_CODE,F.MAKE,F.MODEL,A.CONTRACT_FLEET_ID,A.WEEKEND_MILES,CALENDAR_END_DATE,
X.location, x.equiptype as Equiptype, x.Owned_Flag,x.Purchase_Date,x.State_Licensed, x.Equipment_Status as equip_status, x.EquipStatus
FROM (SELECT CONTRACT_FLEET_ID, MAX(WEEKEND_MILES) WEEKEND_MILES, CALENDAR_END_DATE FROM CL_WEEKEND_MILES_STATUS_T GROUP BY CONTRACT_FLEET_ID, CALENDAR_END_DATE) A
INNER JOIN [CL_CONTRACT_FLEET_T] E ON A.CONTRACT_FLEET_ID = E.CONTRACT_FLEET_ID
INNER JOIN [WI_FLEET_MASTER_T] F ON E.WI_FLEET_ID = F.WI_FLEET_ID 
INNER JOIN [WI_CONTRACT_MASTER_T] G ON E.WI_CONTRACT_ID = G.WI_CONTRACT_ID 
LEFT JOIN dbo.vw_Equipment_Master X ON LTRIM(RTRIM(X.Equipment_code)) = LTRIM(RTRIM(F.EQUIPMENT_CODE))

GO
/****** Object:  View [dbo].[GET_CONTRACT_FLEET_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[GET_CONTRACT_FLEET_V]
AS
	SELECT		CONTRACT_FLEET_ID AS Contract_Fleet_ID, 
				CF.WI_FLEET_ID AS WI_Fleet_ID, 
				[USER_ID] AS [User_ID], 
				WI_CONTRACT_ID	AS WI_Contract_ID, 
				ISACTIVE	AS IsActive, 
				FM.MAKE AS MAke, 
				FM.EQUIPMENT_DESCRIPTION AS Equipment_Description, 
				FM.MODEL AS Model,
				FM.EQUIPMENT_CODE AS Equipment_Code, 
				FM.EQUIPMENT_TYPE AS Equipment_Type, 
				FM.[YEAR] AS [Year], 
				FM.LICENSE_NUMBER As License_Number, 
				FM.METER_TYPE AS Meter_Type, 
				FM.Equipment_Status, 
				FM.Division_Code,
				FM.Equipment_Retired, 
				FM.Company_Code, 
				CF.WEEKEND_MILES AS Weekend_Miles,
				FM.Last_Meter as Spectrum_Miles,
				CF.Comments
	FROM		CL_CONTRACT_FLEET_T AS CF	
	INNER JOIN	WI_FLEET_MASTER_T AS FM	ON FM.WI_FLEET_ID = CF.WI_FLEET_ID
	--WHERE		ISNULL(CF.[ISACTIVE], 1) = 1;
GO
/****** Object:  View [dbo].[GET_PAYITEM_EQUIPMENT_UNIQUE_WBS_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[GET_PAYITEM_EQUIPMENT_UNIQUE_WBS_V]
AS
	SELECT	DISTINCT JPI.JOB_ID, PIM.WBS_CODE
	FROM	CL_JOB_PAYITEM_T JPI 
	INNER JOIN WI_PAYITEM_MASTER_T PIM ON PIM.WI_PAYITEM_ID = JPI.WI_PAYITEM_ID 
	WHERE	ISNULL(JPI.ISACTIVE, 1) = 1 


GO
/****** Object:  View [dbo].[GET_JOB_EQUIPMENT_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [dbo].[GET_JOB_EQUIPMENT_V]
AS
SELECT      JE.JOB_EQUIPMENT_ID, JE.JOB_ID, JE.CONTRACT_FLEET_ID, CF.WI_Fleet_ID, CF.Equipment_Code, CF.Equipment_Description, JE.WI_PAYITEM_ID, PIM.WBS_CODE, JE.HOURS, JE.EQUIPMENT_CHARGE, 
			JE.SERVICED, JE.LAST_SERVICED_DATE, 0 AS Status_Flag, C.COMMENT_ID, C.COMMENT_DESC, CF.WI_Contract_ID, JE.TRANSFER_TO_COMPANY, ISNULL(CF.IsActive, 1) AS IsActive
			, ISNULL(JE.ISACTIVE, 1) AS Job_Equipment_Status
FROM        dbo.CL_JOB_EQUIPMENT_T AS JE 
INNER JOIN dbo.GET_CONTRACT_FLEET_V AS CF ON CF.Contract_Fleet_ID = JE.CONTRACT_FLEET_ID 
INNER JOIN dbo.GET_PAYITEM_EQUIPMENT_UNIQUE_WBS_V AS PIM ON PIM.JOB_ID = JE.JOB_ID AND PIM.WBS_CODE = JE.WBS_CODE 
LEFT OUTER JOIN dbo.CL_COMMENT_T AS C ON C.JOB_ID = JE.JOB_ID AND C.COMMENT_TYPE = 'E'



GO
/****** Object:  View [dbo].[GET_JOB_LABORS_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
 

CREATE VIEW [dbo].[GET_JOB_LABORS_V]
AS
SELECT JL.JOB_LABOR_ID, JL.JOB_ID, JL.FOREMAN_CREW_ID, CC.EMPLOYEE_INFO, CC.EMPLOYEE_ID, CC.EMPLOYEE_NAME, JL.WI_PAYITEM_ID, JL.WBS_Code, JL.WBS_DESCRIPTION, JL.STANDARD_HOURS, JL.OT_HOURS, JL.DT_HOURS, 
                  JL.PER_DIEM, JL.PER_DIEM_TYPE, JL.RIG_RENTALS, JL.MISC_CODE, JL.TRAVEL_PAY, JL.WAIT_TIME_HOURS, JL.PAY_LEVEL, JL.UNION_CODE, JL.WI_CITY_ID, CM.CITY_CODE, C.COMMENT_ID, C.COMMENT_DESC, 
                  CC.WI_CONTRACT_ID, JL.PAID_TIME_OFF, JL.HOLIDAY_PAY, JL.AUTO_ALLOWANCE, JL.OVERRIDES, ISNULL(CC.ISACTIVE, 1) AS IsActive, ISNULL(JL.ISACTIVE, 1) AS Job_Labor_Status, JL.SICK_LEAVE_TYPE
FROM     dbo.CL_JOB_LABOR_T AS JL INNER JOIN
                  dbo.GET_CONTRACT_CREW_V AS CC ON CC.FOREMAN_CREW_ID = JL.FOREMAN_CREW_ID INNER JOIN
                  dbo.WI_CITYCODE_MASTER_T AS CM ON CM.WI_CITY_ID = JL.WI_CITY_ID LEFT OUTER JOIN
                  dbo.CL_COMMENT_T AS C ON C.JOB_ID = JL.JOB_ID AND C.COMMENT_TYPE = 'L'
 
GO
/****** Object:  View [dbo].[GET_WI_CREW_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO





	CREATE VIEW [dbo].[GET_WI_CREW_V]
	AS
			SELECT	[WI_EMPLOYEE_ID], [EMPLOYEE_ID], [EMPLOYEE_NAME], [TYPE], [PROJECT], [EMAIL_ADDRESS],
					[CLASSIFICATION], [TERMINATION_DATE], WI_COMPANY_ID, EM.COMPANY_CODE, [ALPHASORT], [ADDRESS],
					[CITY_ID], [STATE], [ZIP], [STATUS], [DEPARTMENT_CODE] 
			FROM	[GET_WI_EMPLOYEE_MASTER_V] EM
			LEFT	JOIN GET_WI_COMPANY_V CM ON CM.COMPANY_CODE = LTRIM(RTRIM(EM.COMPANY_CODE))
			WHERE	[STATUS]='A' --AND EM.EMPLOYEE_ID NOT IN (SELECT ISNULL(EMPLOYEE_ID,'') FROM GET_USERS_V)


GO
/****** Object:  UserDefinedFunction [dbo].[GET_WEEK_START_END_DATE_FN]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[GET_WEEK_START_END_DATE_FN]
( @WeekDay	AS DATETIME )
RETURNS table
AS
RETURN (
SELECT  DATEADD(DAY, 1 - DATEPART(WEEKDAY, @WeekDay), CAST(@WeekDay AS DATE)) AS WEEK_START_DATE,
		DATEADD(DAY, 7 - DATEPART(WEEKDAY, @WeekDay), CAST(@WeekDay AS DATE)) AS WEEK_END_DATE
)

GO
/****** Object:  View [db_owner].[Geographical_View]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [db_owner].[Geographical_View]
AS
SELECT TOP (100) PERCENT CONVERT(date, JPT.CREATED_ON) AS EntryDate, JMT.JOB_NUMBER, JPT.STREET_ADDRESS + ', ' + CCM.CITY_CODE + ', ' + CCM.STATE_CODE AS EntryLocation, 
             JMT.ADDRESS_1 + ' ' + JMT.ADDRESS_2 + ' ' + JMT.CITY + ', ' + JMT.STATE + ' ' + JMT.ZIP_CODE AS JobLocation, JMT.CUSTOMER_CODE, JMT.CONTRACT_NUMBER, dbo.CL_USER.USER_NAME AS Foreman, dbo.CL_JOB_STATUS_T.JOB_STATUS_NAME AS JobStatus, 
             JT.REVENUE_EXPORTED
FROM   dbo.CL_USER INNER JOIN
             dbo.CL_JOB_T AS JT ON dbo.CL_USER.USER_ID = JT.USER_ID INNER JOIN
             dbo.CL_JOB_STATUS_T ON JT.JOB_STATUS_ID = dbo.CL_JOB_STATUS_T.JOB_STATUS_ID RIGHT OUTER JOIN
             dbo.CL_JOB_PAYITEM_T AS JPT LEFT OUTER JOIN
             dbo.WI_CITYCODE_MASTER_T AS CCM ON JPT.WI_CITY_ID = CCM.WI_CITY_ID ON JT.JOB_ID = JPT.JOB_ID LEFT OUTER JOIN
             dbo.WI_JOB_MASTER_T AS JMT ON JT.WI_JOB_ID = JMT.WI_JOB_ID
ORDER BY EntryDate DESC
GO
/****** Object:  View [db_owner].[vw_Images_Captured]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [db_owner].[vw_Images_Captured]
AS
SELECT DISTINCT 
                         TOP (100) PERCENT JT.CREATED_ON AS EntryDate, JMT.JOB_NUMBER, JMT.ADDRESS_1 + ' ' + JMT.ADDRESS_2 + ' ' + JMT.CITY + ', ' + JMT.STATE + ' ' + JMT.ZIP_CODE AS JobLocation, JMT.CUSTOMER_CODE, 
                         JMT.CONTRACT_NUMBER, dbo.CL_USER.USER_NAME AS Foreman,
                             (SELECT        COUNT(ID) AS Expr1
                               FROM            P360_Images.dbo.CrewLink_Images AS CI
                               WHERE        (JOB_ID = JT.JOB_ID)) AS Image_Count, JST.JOB_STATUS_NAME AS EntryStatus
FROM            dbo.CL_USER INNER JOIN
                         dbo.CL_JOB_T AS JT ON dbo.CL_USER.USER_ID = JT.USER_ID LEFT OUTER JOIN
                         dbo.WI_JOB_MASTER_T AS JMT ON JT.WI_JOB_ID = JMT.WI_JOB_ID INNER JOIN
                         dbo.CL_JOB_STATUS_T AS JST ON JST.JOB_STATUS_ID = JT.JOB_STATUS_ID
WHERE        ((SELECT        COUNT(ID) AS Expr1
                            FROM            P360_Images.dbo.CrewLink_Images AS CI
                            WHERE        (JOB_ID = JT.JOB_ID)) > 0)
ORDER BY EntryDate DESC
GO
/****** Object:  View [db_owner].[vw_Restoration_Summary]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [db_owner].[vw_Restoration_Summary]
AS
SELECT DISTINCT 
             TOP (100) PERCENT MAIN.CONTRACT_NUMBER, MAIN.JOB_NUMBER, MAIN.JOB_START_DATE, MAIN.JOB_STATUS_NAME, MAIN.USER_ID, FOREMAN.EMPLOYEE_NAME AS FOREMAN_NAME, MAIN.SUPERINTENDENT_COMMENT, MAIN.STREET_ADDRESS, MAIN.WORK_ORDER, 
             MAIN.CITY_CODE, MAIN.CUSTOMER_COMPLAINT, MAIN.TRAFFIC_CONTROL, MAIN.BACKLOG_WORK_DATE, MAIN.SURFACE_TYPE_NAME, MAIN.MATERIAL_TYPE_NAME, MAIN.QTY_LENGTH, MAIN.QTY_WIDTH, MAIN.QTY_DEPTH, MAIN.QTY_COUNT, MAIN.QTY_TOTAL, 
             MAIN.CUTSHEET_COMPETE, MAIN.RESTORATIONT_COMPETE, MAIN.TYPE, MAIN.WI_SUPERINTENDENT_ID, SUPERINTENDENT.EMPLOYEE_NAME AS SUPERINTENDENT_NAME, MAIN.STATE_CODE
FROM   (SELECT JSRT.JOB_SURFACES_REMOVED_ID, JSRT.CL_RESURFACING_ID, JSRT.CL_SURFACE_TYPE_ID, JSRT.CL_MATERIAL_TYPE_ID, JSRT.QTY_LENGTH, JSRT.QTY_WIDTH, JSRT.QTY_DEPTH, JSRT.QTY_TOTAL, JSRT.IS_COMPLETED AS CUTSHEET_COMPETE, 
                           JSRTD.IS_COMPLETED AS RESTORATIONT_COMPETE, JSRT.ISACTIVE, JSRT.QTY_COUNT, JSRT.TYPE, RT.WI_JOB_ID, RT.JOB_START_DATE, RT.JOB_ID, RT.JOB_STATUS_ID, RT.CREATED_ON, RT.CREATED_BY, RT.MODIFIED_ON, RT.MODIFIED_BY, RT.USER_ID, 
                           RT.SUPERINTENDENT_COMMENT, RT.STREET_ADDRESS, RT.WORK_ORDER, RT.WI_CITY_ID, RT.CUSTOMER_COMPLAINT, RT.TRAFFIC_CONTROL, RT.BACKLOG_WORK_DATE, STMT.SURFACE_TYPE_NAME, MTMT.MATERIAL_TYPE_NAME, JMT.JOB_NUMBER, 
                           JST.JOB_STATUS_NAME, CMT.CITY_CODE, CMT.STATE_CODE, JMT.CONTRACT_NUMBER, JHI.WI_SUPERINTENDENT_ID
             FROM    dbo.CL_JOB_SURFACES_REMOVED_T AS JSRT WITH (NOLOCK) INNER JOIN
                           dbo.CL_RESURFACING_T AS RT WITH (NOLOCK) ON JSRT.CL_RESURFACING_ID = RT.CL_RESURFACING_ID INNER JOIN
                           dbo.CL_SURFACE_TYPE_MASTER_T AS STMT WITH (NOLOCK) ON JSRT.CL_SURFACE_TYPE_ID = STMT.CL_SURFACE_TYPE_ID INNER JOIN
                           dbo.CL_MATERIAL_TYPE_MASTER_T AS MTMT WITH (NOLOCK) ON JSRT.CL_MATERIAL_TYPE_ID = MTMT.CL_MATERIAL_TYPE_ID INNER JOIN
                           dbo.WI_JOB_MASTER_T AS JMT WITH (NOLOCK) ON RT.WI_JOB_ID = JMT.WI_JOB_ID INNER JOIN
                           dbo.CL_JOB_STATUS_T AS JST WITH (NOLOCK) ON RT.JOB_STATUS_ID = JST.JOB_STATUS_ID INNER JOIN
                           dbo.WI_CITYCODE_MASTER_T AS CMT WITH (NOLOCK) ON RT.WI_CITY_ID = CMT.WI_CITY_ID INNER JOIN
                           dbo.CL_USER AS UT WITH (NOLOCK) ON RT.USER_ID = UT.USER_ID INNER JOIN
                           dbo.CL_JOB_HEADER_INFO_T AS JHI WITH (NOLOCK) ON UT.USER_ID = JHI.WI_FOREMAN_ID INNER JOIN
                           dbo.CL_JOB_SURFACES_RESTORED_T AS JSRTD ON RT.CL_RESURFACING_ID = JSRTD.CL_RESURFACING_ID
             WHERE  (RT.JOB_STATUS_ID <> 5)) AS MAIN INNER JOIN
             dbo.CL_USER AS UT_FOREMAN WITH (NOLOCK) ON MAIN.USER_ID = UT_FOREMAN.USER_ID INNER JOIN
             dbo.WI_EMPLOYEE_MASTER_T AS FOREMAN WITH (NOLOCK) ON UT_FOREMAN.WI_EMPLOYEE_ID = FOREMAN.WI_EMPLOYEE_ID INNER JOIN
             dbo.WI_EMPLOYEE_MASTER_T AS SUPERINTENDENT WITH (NOLOCK) ON MAIN.WI_SUPERINTENDENT_ID = SUPERINTENDENT.WI_EMPLOYEE_ID INNER JOIN
             dbo.CL_USER AS C_BY WITH (NOLOCK) ON MAIN.CREATED_BY = C_BY.USER_ID INNER JOIN
             dbo.CL_USER AS M_BY WITH (NOLOCK) ON MAIN.CREATED_BY = M_BY.USER_ID
WHERE (MAIN.JOB_STATUS_ID IN (1, 2, 4, 7)) AND (SUPERINTENDENT.STATUS = 'A') AND (MAIN.ISACTIVE = 1)
ORDER BY FOREMAN_NAME, MAIN.JOB_START_DATE
GO
/****** Object:  View [dbo].[AUDIT_EMPLOYEE_STATUSES_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO




CREATE VIEW [dbo].[AUDIT_EMPLOYEE_STATUSES_V]
AS
Select Distinct
	AUD.Employee_ID, 
	AUD.USER_NAME, 
	AUD.COMPANY_CODE,
	--SM.STATUS_ID,
	SM.STATUS,
	SM.STATUS_DESCRIPTION,
	STATUS_TYPE,
	AUD.WI_Employee_ID,
	AUD.CL_USER_ID as USER_ID,
	AUD.LAST_LOGIN
From 
	AUDIT_EMPLOYEE_STATUSES AUD
		JOIN 
	AUDIT_STATUS_MASTER SM
		on SM.COMPANY_CODE = AUD.COMPANY_CODE and SM.STATUS_ID = AUD.STATUS_ID-- where employeE_id = '99-999'

GO
/****** Object:  View [dbo].[Geographical_View]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[Geographical_View]
AS
	SELECT --TOP (100) PERCENT 
		CONVERT(date, JPT.CREATED_ON) AS EntryDate
		, JMT.JOB_NUMBER
		, concat(JPT.STREET_ADDRESS, ', ', CCM.CITY_CODE, ', ', CCM.STATE_CODE) AS EntryLocation
		, concat(JMT.ADDRESS_1, ' ', JMT.ADDRESS_2, ' ' + JMT.CITY, ', ', JMT.STATE, ' ', JMT.ZIP_CODE) AS JobLocation
		, JMT.CUSTOMER_CODE
		, JMT.CONTRACT_NUMBER
		, u.USER_NAME AS Foreman
		, js.JOB_STATUS_NAME AS JobStatus
		, JT.REVENUE_EXPORTED
		,JMT.COMPANY_CODE
		,JMT.DIVISION
	FROM   dbo.CL_USER  u
	INNER JOIN dbo.CL_JOB_T JT ON 
		u.USER_ID = JT.USER_ID 

	INNER JOIN dbo.CL_JOB_STATUS_T js ON 
		JT.JOB_STATUS_ID = js.JOB_STATUS_ID 

	RIGHT OUTER JOIN dbo.CL_JOB_PAYITEM_T JPT 

	LEFT OUTER JOIN dbo.WI_CITYCODE_MASTER_T CCM ON 
		JPT.WI_CITY_ID = CCM.WI_CITY_ID ON JT.JOB_ID = JPT.JOB_ID

	LEFT OUTER JOIN dbo.WI_JOB_MASTER_T  JMT ON 
		JT.WI_JOB_ID = JMT.WI_JOB_ID
	--ORDER BY EntryDate DESC
GO
/****** Object:  View [dbo].[GET_ACL_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[GET_ACL_V]
AS

SELECT	ACL_ID, ACL.USER_ROLE_ID, UR.USER_ROLE_NAME, ACL.USER_MODULE_ID, UM.USER_MODULE_NAME,
		ACL.USER_ACCESS_ID, UAT.USER_ACCESS_TYPE      
FROM CL_ACL_T ACL 
INNER JOIN CL_USER_ROLES_T UR ON UR.USER_ROLE_ID = ACL.USER_ROLE_ID
INNER JOIN CL_USER_MODULES_T UM ON UM.USER_MODULE_ID = ACL.USER_MODULE_ID  
INNER JOIN CL_USER_ACCESS_TYPE_T UAT ON UAT.USER_ACCESS_ID = ACL.USER_ACCESS_ID 
WHERE	UR.ISACTIVE = 1 AND UM.ISACTIVE = 1 AND UAT.ISACTIVE = 1

--SELECT [USER_ID], EM.TITLE, [USER_NAME], U.WI_EMPLOYEE_ID, U.USER_ROLE_ID, USER_ROLE_NAME, USER_MODULE_ID, USER_MODULE_NAME
--FROM CL_USER U
--INNER JOIN GET_WI_EMPLOYEE_MASTER_V EM ON EM.WI_EMPLOYEE_ID = U.WI_EMPLOYEE_ID
--INNER JOIN CL_USER_ROLES_T UR ON UR.USER_ROLE_ID = U.USER_ROLE_ID 
--INNER JOIN CL_USER_MODULES_T UM ON UM.USER_ROLE_ID = UR.USER_ROLE_ID  
--WHERE UR.ISACTIVE = 1 AND UM.ISACTIVE = 1

GO
/****** Object:  View [dbo].[GET_JOB_PAYITEM_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[GET_JOB_PAYITEM_V]
AS

	SELECT JPI.Job_ID, JPI.Job_Payitem_ID, JPI.WI_Payitem_ID, WPI.Payitem, WPI.WBS_Code, WPI.WBS_Description, UOM
	FROM CL_JOB_PAYITEM_T JPI
	INNER JOIN WI_PAYITEM_MASTER_T WPI ON WPI.WI_PAYITEM_ID = JPI.WI_PAYITEM_ID 
	WHERE ISACTIVE = 1


GO
/****** Object:  View [dbo].[GET_JOB_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[GET_JOB_V]
AS 
	SELECT	JT.[USER_ID], JT.JOB_START_DATE, JM.JOB_NUMBER, JT.JOB_STATUS_ID, JT.JOB_ID, JT.WI_JOB_ID 
	FROM	CL_JOB_T AS JT
	JOIN	WI_JOB_MASTER_T AS JM ON JT.WI_JOB_ID = JM.WI_JOB_ID 
	WHERE	JM.[STATUS] = 'A' --OR JM.[STATUS] = 'N'



GO
/****** Object:  View [dbo].[GET_LABOR_PAYITEM_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[GET_LABOR_PAYITEM_V]
AS

	SELECT	JPI.JOB_PAYITEM_ID, JPI.JOB_ID, JPI.WI_PAYITEM_ID, PIM.WBS_CODE, JPI.WI_CITY_ID, CC.CITY_CODE  
	FROM	CL_JOB_PAYITEM_T JPI 
	INNER JOIN WI_PAYITEM_MASTER_T PIM ON PIM.WI_PAYITEM_ID = JPI.WI_PAYITEM_ID 
	INNER JOIN WI_CITYCODE_MASTER_T CC ON CC.WI_CITY_ID = JPI.WI_CITY_ID
	WHERE	ISNULL(JPI.ISACTIVE, 1) = 1


GO
/****** Object:  View [dbo].[GET_PAYITEM_UNIQUE_WBS_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[GET_PAYITEM_UNIQUE_WBS_V]
AS

	SELECT	DISTINCT JPI.JOB_ID, PIM.WBS_CODE, PM.WBS_DESCRIPTION, JPI.WI_CITY_ID, LTRIM(RTRIM(CC.CITY_CODE)) AS CITY_CODE, 0 AS WI_PAYITEM_ID
	FROM	CL_JOB_PAYITEM_T JPI 
	CROSS APPLY
		(SELECT TOP 1 WBS_CODE, WBS_DESCRIPTION FROM WI_PAYITEM_MASTER_T PM WHERE PM.WI_PAYITEM_ID = JPI.WI_PAYITEM_ID) AS PM
	INNER JOIN WI_PAYITEM_MASTER_T PIM ON PIM.WI_PAYITEM_ID = JPI.WI_PAYITEM_ID 
	INNER JOIN WI_CITYCODE_MASTER_T CC ON CC.WI_CITY_ID = JPI.WI_CITY_ID
	WHERE	ISNULL(JPI.ISACTIVE, 1) = 1 


GO
/****** Object:  View [dbo].[GET_WEEKEND_MILES_STATUS_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[GET_WEEKEND_MILES_STATUS_V]
AS

SELECT	WEEKEND_MILES_STATUS_ID, CONTRACT_FLEET_ID, WEEKEND_MILES, CALENDAR_START_DATE, CALENDAR_END_DATE, 
		CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, ISACTIVE
FROM	CL_WEEKEND_MILES_STATUS_T
WHERE	ISACTIVE = 1



GO
/****** Object:  View [dbo].[GET_WI_FLEET_V]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

	CREATE VIEW [dbo].[GET_WI_FLEET_V]
	AS
		SELECT 		[WI_FLEET_ID] AS WI_Fleet_ID, LTRIM(RTRIM(FM.COMPANY_CODE)) AS Company_Code, 
					[EQUIPMENT_DESCRIPTION] AS Equipment_Description, [EQUIPMENT_CODE] AS Equipment_Code, 
					[EQUIPMENT_TYPE] AS Equipment_Type, [YEAR] AS [YEAR], LICENSE_NUMBER AS License_Number,
					[METER_TYPE] AS Meter_Type, EQUIPMENT_STATUS AS Equipment_Status,
					DIVISION_CODE AS Division_Code, EQUIPMENT_RETIRED AS Equipment_Retired,
					[MAKE] AS Make, [MODEL] AS Model, CM.WI_COMPANY_ID AS Company_ID
		FROM		WI_FLEET_MASTER_T AS FM
		LEFT JOIN	WI_COMPANY_MASTER_T AS CM ON LTRIM(RTRIM(CM.COMPANY_CODE)) = LTRIM(RTRIM(FM.COMPANY_CODE))


GO
/****** Object:  View [dbo].[vw_Company_Master]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vw_Company_Master]
AS 

	SELECT WI_COMPANY_ID, LTRIM(RTRIM(COMPANY_CODE)) AS COMPANY_CODE, COMPANY_NAME  
	FROM   WI_COMPANY_MASTER_T 
	







GO
/****** Object:  View [dbo].[vw_Hierarchy_Reconstructed_HR]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vw_Hierarchy_Reconstructed_HR]
AS

            SELECT e.Child AS Global,ISNULL(d.Child,e.Child) AS Region ,ISNULL(c.Child,ISNULL(d.Child,e.Child) ) AS GroupName ,ISNULL(b.Child,ISNULL(c.Child,d.Child)) AS Company, ISNULL(a.Child,ISNULL(b.Child,ISNULL(c.Child,d.Child)))AS Opu, ISNULL(a.Company_Code,ISNULL(b.Company_Code,ISNULL(c.Company_Code,d.Company_Code)))AS CoCode
			FROM [tb_HR_Hierarchy_Parent_Child] a RIGHT OUTER JOIN [tb_HR_Hierarchy_Parent_Child] b ON a.ParentID = b.Id
			RIGHT OUTER JOIN [tb_HR_Hierarchy_Parent_Child] c ON b.ParentID = c.Id
			RIGHT OUTER JOIN [tb_HR_Hierarchy_Parent_Child] d ON c.ParentID = d.Id
			RIGHT OUTER JOIN [tb_HR_Hierarchy_Parent_Child] e ON d.ParentID = e.Id
			WHERE e.Child = 'Total Combined' or e.Child = 'Total Other'

GO
/****** Object:  View [dbo].[vw_Images_Captured]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

Create VIEW [dbo].[vw_Images_Captured]
AS

	SELECT DISTINCT  --TOP (100) PERCENT 
		JT.CREATED_ON AS EntryDate
		, JMT.JOB_NUMBER
		, Concat(JMT.ADDRESS_1, ' ', JMT.ADDRESS_2, ' ', JMT.CITY, ', ', JMT.STATE, ' ', JMT.ZIP_CODE) AS JobLocation
		, JMT.CUSTOMER_CODE
		, JMT.CONTRACT_NUMBER
		, u.USER_NAME AS Foreman
		, (SELECT
				COUNT(ID) AS Expr1
			FROM P360_Images.dbo.CrewLink_Images AS CI
			 WHERE        
				(JOB_ID = JT.JOB_ID)
		) AS Image_Count
		, JST.JOB_STATUS_NAME AS EntryStatus
	FROM dbo.CL_USER u
	INNER JOIN dbo.CL_JOB_T AS JT ON 
		u.USER_ID = JT.USER_ID 
	LEFT OUTER JOIN dbo.WI_JOB_MASTER_T AS JMT ON 
		JT.WI_JOB_ID = JMT.WI_JOB_ID 
	INNER JOIN  dbo.CL_JOB_STATUS_T AS JST ON 
		JST.JOB_STATUS_ID = JT.JOB_STATUS_ID
	WHERE        
		(
			(SELECT
				COUNT(ID) AS Expr1
			FROM P360_Images.dbo.CrewLink_Images AS CI
			WHERE        
			(JOB_ID = JT.JOB_ID)
		) > 0)
	--ORDER BY EntryDate DESC
GO
/****** Object:  View [dbo].[vw_Job_Status]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vw_Job_Status]
AS 
	SELECT	
	
	WIS.EMPLOYEE_NAME as SuperintendentName,
	WIS.WI_EMPLOYEE_ID as SuperintendentWIEmpID,
	WIT.WI_EMPLOYEE_ID as ForemanEmpID, 
	WIT.EMPLOYEE_NAME as Foreman, 
	CU.WI_EMPLOYEE_ID, 
	JM.CONTRACT_NUMBER, 
	JM.COMPANY_CODE, 
	JM.JOB_NUMBER, 
	JM.JOB_TYPE, 
	JT.JOB_START_DATE,  
	ST.JOB_STATUS_NAME, 
	JT.JOB_ID, 
	JT.WI_JOB_ID 

	FROM	CL_JOB_T AS JT
	JOIN	WI_JOB_MASTER_T AS JM ON JT.WI_JOB_ID = JM.WI_JOB_ID
	JOIN    CL_JOB_STATUS_T ST ON JT.JOB_STATUS_ID = ST.JOB_STATUS_ID  
	JOIN    CL_USER AS CU ON JT.USER_ID = CU.USER_ID
	JOIN    WI_EMPLOYEE_MASTER_T WIT ON CU.WI_EMPLOYEE_ID = WIT.WI_EMPLOYEE_ID
	--JOIN    vw_Superintendent_Master SM ON JM.SUPERINTENDENT =  SM.EMPLOYEE_ID
	INNER JOIN    (SELECT DISTINCT WI_EMployee_ID,Employee_Name, Employee_Id FROM [WI_EMPLOYEE_MASTER_T] )  WIS ON JM.SUPERINTENDENT = WIS.EMPLOYEE_ID

	WHERE ST.JOB_STATUS_NAME <> 'Deleted'
	--JOIN    WI_CONTRACT_MASTER_T WCM ON JM.CONTRACT_NUMBER = WCM.CONTRACT_NUMBER   








GO
/****** Object:  View [dbo].[vw_Lockdown_Overview]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[vw_Lockdown_Overview] AS
  SELECT EM.EMPLOYEE_NAME as SuperintendentName, U.WI_EMPLOYEE_ID as SuperintendentWIEmpID, EM.COmpany_code, EM.EMPLOYEE_NAME,CALENDAR_START_DATE, CALENDAR_END_DATE, LOCK_DOWN_STATUS, MODIFIED_ON FROM [CL_LOCK_DOWN_T] LD
  INNER JOIN CL_USER U ON LD.USER_ID = U.USER_ID
  INNER JOIN WI_EMPLOYEE_MASTER_T EM ON U.WI_EMPLOYEE_ID = EM.WI_EMPLOYEE_ID






GO
/****** Object:  View [dbo].[vw_Missing_CustomerCodes_Mapping]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[vw_Missing_CustomerCodes_Mapping]  as
SELECT DISTINCT
		A.[COMPANY_CODE],
		A.[CUSTOMER_CODE],
		A.[CONTRACT_NUMBER],
		'' [Last_Date_Used],
		'' [Status],
		'' [Deleted],
		'' [Contract_Status],
		'' [Report_Mapping_Needed],
		'' [VP],
		'' [Director],
		'' [Ops_Manager],
		'' [PM],
		'' [CUSTOMER_NAME],
		'' [Report_Mapping_Vetted],
		'' [Adj Cust Name]
FROM
	 (select  DISTINCT M.[COMPANY_CODE],M.[CUSTOMER_CODE],M.[CONTRACT_NUMBER]
	from WI_JOB_MASTER_T M 
	LEFT JOIN [CL_JOB_T] C ON M.WI_JOB_ID=C.WI_JOB_ID
	WHERE C.JOB_START_DATE>= '2018-01-01' and M.SOURCE<>'CL'
	except
	select  V.[COMPANY_CODE],V.[CUSTOMER_CODE],V.[CONTRACT_NUMBER]
	from tb_New_Contract_VP_Manager V) A
GO
/****** Object:  View [dbo].[VW_PI_Mapping]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE View [dbo].[VW_PI_Mapping] as
	Select MAP.PAYITEM, MAP.PI_DESC as PI_DESCRIPTION, MAP.WBS_CODE, MAP.CONTRACT_NUMBER, MAP.Company_code, MAP.UnitLength, MAP.Description as Description1, X.Description as Description2   from 
	(Select Distinct A.PAYITEM, C.DESCRIPTION as PI_DESC, C.WBS_CODE, A.CONTRACT_NUMBER, A.Company_code, A.UnitLength, B.Description from CL_REPORTING_MAPPING A
	inner join CL_REPORTING_CATEGORY B on A.CL_REPORTING_CATEGORY_ID = B.CL_REPORTING_CATEGORY_ID
	left Join (Select Distinct COMPANY_CODE, CONTRACT_NUMBER, PAYITEM, WBS_CODE, Description from WI_PAYITEM_MASTER_T  where INACTIVEFLAG = 0 ) C on A.PAYITEM = C.PAYITEM AND A.CONTRACT_NUMBER = C.CONTRACT_NUMBER AND A.COMPANY_CODE = C.COMPANY_CODE AND A.DESCRIPTION = C.DESCRIPTION 
	where B.Enabled = 1) MAP 
	Left Join CL_REPORTING_MAPPING_OVERRIDE ORide on MAP.PAYITEM = ORide.PAYITEM and MAP.WBS_CODE = ORide.WBS_CODE and MAP.COMPANY_CODE = ORide.COMPANY_CODE AND MAP.CONTRACT_NUMBER = ORide.CONTRACT_NUMBER
	Left Join  CL_REPORTING_CATEGORY  X on ORide.CL_REPORTING_CATEGORY_ID = X.CL_REPORTING_CATEGORY_ID


GO
/****** Object:  View [dbo].[vw_Restoration_Summary]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[vw_Restoration_Summary]
AS
	SELECT DISTINCT --TOP (100) PERCENT 
		MAIN.CONTRACT_NUMBER
		, MAIN.JOB_NUMBER
		, MAIN.JOB_START_DATE
		, MAIN.JOB_STATUS_NAME
		, MAIN.USER_ID
		, FOREMAN.EMPLOYEE_NAME AS FOREMAN_NAME
		, MAIN.SUPERINTENDENT_COMMENT
		, MAIN.STREET_ADDRESS
		, MAIN.WORK_ORDER
		, MAIN.CITY_CODE
		, MAIN.CUSTOMER_COMPLAINT
		, MAIN.TRAFFIC_CONTROL
		, MAIN.BACKLOG_WORK_DATE
		, MAIN.SURFACE_TYPE_NAME
		, MAIN.MATERIAL_TYPE_NAME
		, MAIN.QTY_LENGTH
		, MAIN.QTY_WIDTH
		, MAIN.QTY_DEPTH
		, MAIN.QTY_COUNT
		, MAIN.QTY_TOTAL
		, MAIN.CUTSHEET_COMPETE, MAIN.RESTORATIONT_COMPETE
		, MAIN.TYPE
		, MAIN.WI_SUPERINTENDENT_ID
		, SUPERINTENDENT.EMPLOYEE_NAME AS SUPERINTENDENT_NAME
		, MAIN.STATE_CODE
	FROM   
		(
			SELECT 
				JSRT.JOB_SURFACES_REMOVED_ID
				, JSRT.CL_RESURFACING_ID
				, JSRT.CL_SURFACE_TYPE_ID
				, JSRT.CL_MATERIAL_TYPE_ID
				, JSRT.QTY_LENGTH
				, JSRT.QTY_WIDTH
				, JSRT.QTY_DEPTH
				, JSRT.QTY_TOTAL
				, JSRT.IS_COMPLETED AS CUTSHEET_COMPETE
				, JSRTD.IS_COMPLETED AS RESTORATIONT_COMPETE
				, JSRT.ISACTIVE
				, JSRT.QTY_COUNT
				, JSRT.TYPE
				, RT.WI_JOB_ID
				, RT.JOB_START_DATE
				, RT.JOB_ID
				, RT.JOB_STATUS_ID
				, RT.CREATED_ON
				, RT.CREATED_BY
				, RT.MODIFIED_ON
				, RT.MODIFIED_BY
				, RT.USER_ID
				,  RT.SUPERINTENDENT_COMMENT
				, RT.STREET_ADDRESS
				, RT.WORK_ORDER
				, RT.WI_CITY_ID
				, RT.CUSTOMER_COMPLAINT
				, RT.TRAFFIC_CONTROL
				, RT.BACKLOG_WORK_DATE
				, STMT.SURFACE_TYPE_NAME
				, MTMT.MATERIAL_TYPE_NAME
				, JMT.JOB_NUMBER
				, JST.JOB_STATUS_NAME
				, CMT.CITY_CODE
				, CMT.STATE_CODE
				, JMT.CONTRACT_NUMBER
				, JHI.WI_SUPERINTENDENT_ID
			FROM    dbo.CL_JOB_SURFACES_REMOVED_T AS JSRT WITH (NOLOCK) 
			INNER JOIN dbo.CL_RESURFACING_T AS RT WITH (NOLOCK) ON 
				JSRT.CL_RESURFACING_ID = RT.CL_RESURFACING_ID 

			INNER JOIN dbo.CL_SURFACE_TYPE_MASTER_T AS STMT WITH (NOLOCK) ON 
				JSRT.CL_SURFACE_TYPE_ID = STMT.CL_SURFACE_TYPE_ID 

			INNER JOIN dbo.CL_MATERIAL_TYPE_MASTER_T AS MTMT WITH (NOLOCK) ON 
				JSRT.CL_MATERIAL_TYPE_ID = MTMT.CL_MATERIAL_TYPE_ID 

			INNER JOIN dbo.WI_JOB_MASTER_T AS JMT WITH (NOLOCK) ON 
				RT.WI_JOB_ID = JMT.WI_JOB_ID 

			INNER JOIN dbo.CL_JOB_STATUS_T AS JST WITH (NOLOCK) ON 
				RT.JOB_STATUS_ID = JST.JOB_STATUS_ID 

			INNER JOIN dbo.WI_CITYCODE_MASTER_T AS CMT WITH (NOLOCK) ON 
				RT.WI_CITY_ID = CMT.WI_CITY_ID 

			INNER JOIN dbo.CL_USER AS UT WITH (NOLOCK) ON 
				RT.USER_ID = UT.USER_ID 
			INNER JOIN dbo.CL_JOB_HEADER_INFO_T AS JHI WITH (NOLOCK) ON 
				UT.USER_ID = JHI.WI_FOREMAN_ID 
			INNER JOIN dbo.CL_JOB_SURFACES_RESTORED_T AS JSRTD ON 
				RT.CL_RESURFACING_ID = JSRTD.CL_RESURFACING_ID
			WHERE  
				(RT.JOB_STATUS_ID <> 5)
		) AS MAIN 
	INNER JOIN dbo.CL_USER AS UT_FOREMAN WITH (NOLOCK) ON 
		MAIN.USER_ID = UT_FOREMAN.USER_ID 

	INNER JOIN dbo.WI_EMPLOYEE_MASTER_T AS FOREMAN WITH (NOLOCK) ON 
		UT_FOREMAN.WI_EMPLOYEE_ID = FOREMAN.WI_EMPLOYEE_ID 

	INNER JOIN dbo.WI_EMPLOYEE_MASTER_T AS SUPERINTENDENT WITH (NOLOCK) ON 
		MAIN.WI_SUPERINTENDENT_ID = SUPERINTENDENT.WI_EMPLOYEE_ID 

	INNER JOIN dbo.CL_USER AS C_BY WITH (NOLOCK) ON 
		MAIN.CREATED_BY = C_BY.USER_ID 

	INNER JOIN dbo.CL_USER AS M_BY WITH (NOLOCK) ON 
		MAIN.CREATED_BY = M_BY.USER_ID

	WHERE 
		(MAIN.JOB_STATUS_ID IN (1, 2, 4, 7)) 
		AND (SUPERINTENDENT.STATUS = 'A') 
		AND (MAIN.ISACTIVE = 1)
	--ORDER BY FOREMAN_NAME, MAIN.JOB_START_DATE
GO
/****** Object:  View [dbo].[vw_WI_Customer_Contract]    Script Date: 17-11-2022 15:18:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


Create view [dbo].[vw_WI_Customer_Contract]
as
	Select Distinct
		cast(a.CUSTOMER_CODE as varchar(10)) CUSTOMER_CODE
		, cast(b.CONTRACT_NUMBER as varchar(30)) CONTRACT_NUMBER
	From dbo.WI_CUSTOMER_MASTER_T a
	Join dbo.WI_CONTRACT_MASTER_T b on 
		a.WI_CONTRACT_ID = b.WI_CONTRACT_ID
	Where 
		--contract.CONTRACT_NUMBER = @contract 
		--and 
		a.DELETED = -1

GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane1', @value=N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[40] 4[20] 2[20] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
         Begin Table = "CL_USER (dbo)"
            Begin Extent = 
               Top = 224
               Left = 762
               Bottom = 354
               Right = 944
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "JT"
            Begin Extent = 
               Top = 31
               Left = 471
               Bottom = 161
               Right = 724
            End
            DisplayFlags = 280
            TopColumn = 12
         End
         Begin Table = "JPT"
            Begin Extent = 
               Top = 6
               Left = 38
               Bottom = 136
               Right = 224
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "CCM"
            Begin Extent = 
               Top = 208
               Left = 258
               Bottom = 338
               Right = 428
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "JMT"
            Begin Extent = 
               Top = 47
               Left = 850
               Bottom = 177
               Right = 1055
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "CL_JOB_STATUS_T (dbo)"
            Begin Extent = 
               Top = 141
               Left = 1147
               Bottom = 311
               Right = 1407
            End
            DisplayFlags = 280
            TopColumn = 0
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
      Begin ColumnWidths = 9
         Width = 284
         Width = 1500
         Width = 150' , @level0type=N'SCHEMA',@level0name=N'db_owner', @level1type=N'VIEW',@level1name=N'Geographical_View'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane2', @value=N'0
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias = 900
         Table = 1170
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
   End
End
' , @level0type=N'SCHEMA',@level0name=N'db_owner', @level1type=N'VIEW',@level1name=N'Geographical_View'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPaneCount', @value=2 , @level0type=N'SCHEMA',@level0name=N'db_owner', @level1type=N'VIEW',@level1name=N'Geographical_View'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane1', @value=N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[40] 4[20] 2[20] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
         Begin Table = "CL_USER (dbo)"
            Begin Extent = 
               Top = 6
               Left = 38
               Bottom = 136
               Right = 220
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "JT"
            Begin Extent = 
               Top = 6
               Left = 258
               Bottom = 136
               Right = 511
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "JMT"
            Begin Extent = 
               Top = 138
               Left = 470
               Bottom = 268
               Right = 675
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "JST"
            Begin Extent = 
               Top = 270
               Left = 38
               Bottom = 383
               Right = 233
            End
            DisplayFlags = 280
            TopColumn = 0
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
      Begin ColumnWidths = 9
         Width = 284
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias = 1455
         Table = 1170
         Output = 1215
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
   End' , @level0type=N'SCHEMA',@level0name=N'db_owner', @level1type=N'VIEW',@level1name=N'vw_Images_Captured'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane2', @value=N'
End
' , @level0type=N'SCHEMA',@level0name=N'db_owner', @level1type=N'VIEW',@level1name=N'vw_Images_Captured'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPaneCount', @value=2 , @level0type=N'SCHEMA',@level0name=N'db_owner', @level1type=N'VIEW',@level1name=N'vw_Images_Captured'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane1', @value=N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[40] 4[20] 2[20] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
         Begin Table = "MAIN"
            Begin Extent = 
               Top = 9
               Left = 57
               Bottom = 206
               Right = 401
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "UT_FOREMAN"
            Begin Extent = 
               Top = 9
               Left = 458
               Bottom = 206
               Right = 701
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "FOREMAN"
            Begin Extent = 
               Top = 9
               Left = 758
               Bottom = 206
               Right = 1040
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "SUPERINTENDENT"
            Begin Extent = 
               Top = 9
               Left = 1097
               Bottom = 206
               Right = 1379
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "C_BY"
            Begin Extent = 
               Top = 9
               Left = 1436
               Bottom = 206
               Right = 1679
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "M_BY"
            Begin Extent = 
               Top = 207
               Left = 57
               Bottom = 404
               Right = 300
            End
            DisplayFlags = 280
            TopColumn = 0
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias' , @level0type=N'SCHEMA',@level0name=N'db_owner', @level1type=N'VIEW',@level1name=N'vw_Restoration_Summary'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane2', @value=N' = 900
         Table = 1170
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
   End
End
' , @level0type=N'SCHEMA',@level0name=N'db_owner', @level1type=N'VIEW',@level1name=N'vw_Restoration_Summary'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPaneCount', @value=2 , @level0type=N'SCHEMA',@level0name=N'db_owner', @level1type=N'VIEW',@level1name=N'vw_Restoration_Summary'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane1', @value=N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[40] 4[20] 2[20] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
         Begin Table = "JE"
            Begin Extent = 
               Top = 6
               Left = 38
               Bottom = 136
               Right = 268
            End
            DisplayFlags = 280
            TopColumn = 8
         End
         Begin Table = "CF"
            Begin Extent = 
               Top = 138
               Left = 38
               Bottom = 268
               Right = 250
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "PIM"
            Begin Extent = 
               Top = 6
               Left = 306
               Bottom = 102
               Right = 476
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "C"
            Begin Extent = 
               Top = 138
               Left = 288
               Bottom = 268
               Right = 471
            End
            DisplayFlags = 280
            TopColumn = 0
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias = 900
         Table = 1170
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
   End
End
' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'GET_JOB_EQUIPMENT_V'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPaneCount', @value=1 , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'GET_JOB_EQUIPMENT_V'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane1', @value=N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[63] 4[5] 2[14] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
         Begin Table = "JL"
            Begin Extent = 
               Top = 6
               Left = 38
               Bottom = 136
               Right = 249
            End
            DisplayFlags = 280
            TopColumn = 7
         End
         Begin Table = "CC"
            Begin Extent = 
               Top = 138
               Left = 38
               Bottom = 268
               Right = 236
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "CM"
            Begin Extent = 
               Top = 6
               Left = 287
               Bottom = 136
               Right = 457
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "C"
            Begin Extent = 
               Top = 138
               Left = 274
               Bottom = 268
               Right = 457
            End
            DisplayFlags = 280
            TopColumn = 0
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
      Begin ColumnWidths = 9
         Width = 284
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias = 900
         Table = 1170
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
   End
End
' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'GET_JOB_LABORS_V'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPaneCount', @value=1 , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'GET_JOB_LABORS_V'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane1', @value=N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[40] 4[20] 2[20] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
         Begin Table = "WI_CONTRACT_MASTER_T (dbo)"
            Begin Extent = 
               Top = 6
               Left = 38
               Bottom = 136
               Right = 281
            End
            DisplayFlags = 280
            TopColumn = 10
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias = 900
         Table = 1170
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
   End
End
' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'GET_WI_CONTRACT_V'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPaneCount', @value=1 , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'GET_WI_CONTRACT_V'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane1', @value=N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[41] 4[20] 2[12] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
         Begin Table = "WI_CUSTOMER_MASTER_T"
            Begin Extent = 
               Top = 7
               Left = 48
               Bottom = 168
               Right = 264
            End
            DisplayFlags = 280
            TopColumn = 9
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
      Begin ColumnWidths = 9
         Width = 284
         Width = 1200
         Width = 1200
         Width = 1200
         Width = 1200
         Width = 1200
         Width = 1200
         Width = 1200
         Width = 1200
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias = 900
         Table = 1170
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
   End
End
' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'GET_WI_CUSTOMER_V'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPaneCount', @value=1 , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'GET_WI_CUSTOMER_V'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane1', @value=N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[40] 4[20] 2[20] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
         Begin Table = "WI_EMPLOYEE_MASTER_T (dbo)"
            Begin Extent = 
               Top = 7
               Left = 48
               Bottom = 168
               Right = 283
            End
            DisplayFlags = 280
            TopColumn = 0
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
      Begin ColumnWidths = 9
         Width = 284
         Width = 1200
         Width = 1200
         Width = 1200
         Width = 1200
         Width = 1200
         Width = 1200
         Width = 1200
         Width = 1200
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias = 900
         Table = 1170
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
   End
End
' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'GET_WI_EMPLOYEE_MASTER_V'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPaneCount', @value=1 , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'GET_WI_EMPLOYEE_MASTER_V'
GO
