/****** Object:  Table [dbo].[CL_BHNE_ADDITIONAL_INFO_T]    Script Date: 07-06-2022 15:49:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CL_BHNE_ADDITIONAL_INFO_T]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[CL_BHNE_ADDITIONAL_INFO_T](
	[BHNE_ADDITIONAL_INFO_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[JOB_ID] [bigint] NOT NULL,
	[PAY_ITEM_ID] [nvarchar](50) NULL,
	[UNIQUE_ID] [nvarchar](20) NULL,
	[PREMISE_ID] [nvarchar](30) NULL,
	[ADDRESS] [nvarchar](30) NULL,
	[CREATED_ON] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[MODIFIED_ON] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[IS_ACTIVE] [bit] NULL,
	[STREET] [nvarchar](100) NULL,
	[CITY] [nvarchar](100) NULL,
	[STATE] [nvarchar](100) NULL,
 CONSTRAINT [PK_CL_BHNE_ADDITIONAL_INFO_T] PRIMARY KEY CLUSTERED 
(
	[BHNE_ADDITIONAL_INFO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
