SET IDENTITY_INSERT [dbo].[CL_JOB_STATUS_T] ON 
GO
INSERT [dbo].[CL_JOB_STATUS_T] ([JOB_STATUS_ID], [JOB_STATUS_NAME], [ISACTIVE]) VALUES (1, N'Pending', 1)
GO
INSERT [dbo].[CL_JOB_STATUS_T] ([JOB_STATUS_ID], [JOB_STATUS_NAME], [ISACTIVE]) VALUES (2, N'Approved', 1)
GO
INSERT [dbo].[CL_JOB_STATUS_T] ([JOB_STATUS_ID], [JOB_STATUS_NAME], [ISACTIVE]) VALUES (3, N'Rejected', 1)
GO
INSERT [dbo].[CL_JOB_STATUS_T] ([JOB_STATUS_ID], [JOB_STATUS_NAME], [ISACTIVE]) VALUES (4, N'InProgress', 1)
GO
INSERT [dbo].[CL_JOB_STATUS_T] ([JOB_STATUS_ID], [JOB_STATUS_NAME], [ISACTIVE]) VALUES (5, N'Deleted', 1)
GO
INSERT [dbo].[CL_JOB_STATUS_T] ([JOB_STATUS_ID], [JOB_STATUS_NAME], [ISACTIVE]) VALUES (6, N'New', 1)
GO
INSERT [dbo].[CL_JOB_STATUS_T] ([JOB_STATUS_ID], [JOB_STATUS_NAME], [ISACTIVE]) VALUES (7, N'Reviewed', 1)
GO
SET IDENTITY_INSERT [dbo].[CL_JOB_STATUS_T] OFF
GO
INSERT [dbo].[ML_DSR_ADDITIONAL_INFO_MASTER_T] ([ADDITIONAL_INFO_ID], [ADDITIONAL_INFO_NAME], [ISACTIVE], [SECTION], [DISPLAY_ORDER]) VALUES (N'4985f5b3-e506-4a65-9106-091aa8589b36', N'START', 1, NULL, 0)
GO
INSERT [dbo].[ML_DSR_ADDITIONAL_INFO_MASTER_T] ([ADDITIONAL_INFO_ID], [ADDITIONAL_INFO_NAME], [ISACTIVE], [SECTION], [DISPLAY_ORDER]) VALUES (N'1b1a4c1c-65f4-44cd-b110-23fd3cfca8c1', N'MP_OR_ST', 1, NULL, 0)
GO
INSERT [dbo].[ML_DSR_ADDITIONAL_INFO_MASTER_T] ([ADDITIONAL_INFO_ID], [ADDITIONAL_INFO_NAME], [ISACTIVE], [SECTION], [DISPLAY_ORDER]) VALUES (N'2aa58628-6d3b-493d-b241-258f3de0505b', N'REWORK', 1, NULL, 0)
GO
INSERT [dbo].[ML_DSR_ADDITIONAL_INFO_MASTER_T] ([ADDITIONAL_INFO_ID], [ADDITIONAL_INFO_NAME], [ISACTIVE], [SECTION], [DISPLAY_ORDER]) VALUES (N'44eacbda-898c-4177-ac8b-50bba8e812dc', N'TOMORROWS_PLAN', 1, NULL, 0)
GO
INSERT [dbo].[ML_DSR_ADDITIONAL_INFO_MASTER_T] ([ADDITIONAL_INFO_ID], [ADDITIONAL_INFO_NAME], [ISACTIVE], [SECTION], [DISPLAY_ORDER]) VALUES (N'60331e6f-e2f0-4f37-93b3-6da50390acb9', N'WORK_LOCATION', 1, NULL, 0)
GO
INSERT [dbo].[ML_DSR_ADDITIONAL_INFO_MASTER_T] ([ADDITIONAL_INFO_ID], [ADDITIONAL_INFO_NAME], [ISACTIVE], [SECTION], [DISPLAY_ORDER]) VALUES (N'2c50bdf1-5ecc-41cb-a7b8-7a8723185bac', N'STOP', 1, NULL, 0)
GO
INSERT [dbo].[ML_DSR_ADDITIONAL_INFO_MASTER_T] ([ADDITIONAL_INFO_ID], [ADDITIONAL_INFO_NAME], [ISACTIVE], [SECTION], [DISPLAY_ORDER]) VALUES (N'd44dabc7-a14f-47a6-85b9-86cf4c0919ed', N'CLIENT_CONTACT_NAME', 1, NULL, 0)
GO
INSERT [dbo].[ML_DSR_ADDITIONAL_INFO_MASTER_T] ([ADDITIONAL_INFO_ID], [ADDITIONAL_INFO_NAME], [ISACTIVE], [SECTION], [DISPLAY_ORDER]) VALUES (N'7224ee06-80eb-44ad-b16c-8aadc6055c8b', N'SURVEY_TYPE', 1, NULL, 0)
GO
INSERT [dbo].[ML_DSR_ADDITIONAL_INFO_MASTER_T] ([ADDITIONAL_INFO_ID], [ADDITIONAL_INFO_NAME], [ISACTIVE], [SECTION], [DISPLAY_ORDER]) VALUES (N'9320d0f1-15ec-49b8-827f-a83d550ce241', N'COMMENTS', 1, NULL, 0)
GO
INSERT [dbo].[ML_DSR_ADDITIONAL_INFO_MASTER_T] ([ADDITIONAL_INFO_ID], [ADDITIONAL_INFO_NAME], [ISACTIVE], [SECTION], [DISPLAY_ORDER]) VALUES (N'fd9ef421-497e-4336-9472-a8e7a0aa4fe1', N'FOOTAGE', 1, NULL, 0)
GO
INSERT [dbo].[ML_DSR_ADDITIONAL_INFO_MASTER_T] ([ADDITIONAL_INFO_ID], [ADDITIONAL_INFO_NAME], [ISACTIVE], [SECTION], [DISPLAY_ORDER]) VALUES (N'18f0fe32-04ea-4915-abb8-bbb1c8b0505d', N'CLIENT_CONTACT_PHONE', 1, NULL, 0)
GO
INSERT [dbo].[ML_DSR_ADDITIONAL_INFO_MASTER_T] ([ADDITIONAL_INFO_ID], [ADDITIONAL_INFO_NAME], [ISACTIVE], [SECTION], [DISPLAY_ORDER]) VALUES (N'5f7e70b5-2d9b-406b-9bb5-bcd9ab5af974', N'IMPORT_FROM_PREVIOUS_ENTRY', 1, NULL, 0)
GO
INSERT [dbo].[ML_DSR_ADDITIONAL_INFO_MASTER_T] ([ADDITIONAL_INFO_ID], [ADDITIONAL_INFO_NAME], [ISACTIVE], [SECTION], [DISPLAY_ORDER]) VALUES (N'6e735ef7-e485-4baa-b54c-f1af3ccf93c3', N'PO_NUMBER', 1, NULL, 0)
GO
INSERT [dbo].[ML_DSR_ADDITIONAL_INFO_MASTER_T] ([ADDITIONAL_INFO_ID], [ADDITIONAL_INFO_NAME], [ISACTIVE], [SECTION], [DISPLAY_ORDER]) VALUES (N'39bd21fb-9012-4f14-a4aa-f7b12a0793e5', N'WORK_AREA_DESCRIPTION', 1, NULL, 0)
GO
INSERT [dbo].[ML_DSR_ADDITIONAL_INFO_MASTER_T] ([ADDITIONAL_INFO_ID], [ADDITIONAL_INFO_NAME], [ISACTIVE], [SECTION], [DISPLAY_ORDER]) VALUES (N'4b8bb865-113f-4d50-98a9-ffc87e9e597d', N'NARRATIVE_OF_DELAYS', 1, NULL, 0)
GO
SET IDENTITY_INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ON 
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Air Compressor (Up to 160 CFM) or equal ', N'RM0701', N'MM33', 1)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Air Compressor (161 to 185 CFM) or equal    ', N'RM0702', N'MM33', 2)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Air Compressor (186 to 250 CFM) or equal ', N'RM0703', NULL, 3)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Air Compressor (251 to 375 CFM) or equal    ', N'RM0704', N'MM34', 4)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Air Compressor (376 to 425 CFM) or equal ', N'RM0705', NULL, 5)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Air Compressor (426 to 650 CFM) or equal ', N'RM0706', NULL, 6)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Air Compressor (651 to 750 CFM) or equal ', N'RM0707', NULL, 7)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Air Compressor (751 to 825 CFM) or equal ', N'RM0708', NULL, 8)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Air Compressor (826 to 900 CFM) or equal ', N'RM0709', NULL, 9)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Air Compressor (901 to 1300 CFM) or equal ', N'RM0710', NULL, 10)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Air Compressor (1301 to 1600 CFM) or equal ', N'RM0711', NULL, 11)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Air Compressor - Air Drier ', N'RM0712', NULL, 12)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'ATV - John Deere Gator 4x4 or equal', N'RM1012', N'MM23', 13)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Blasting - BRS - 30" to 36" Sandblast Head ', NULL, N'MM03', 14)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Blasting - BRS - 30" to 36" Waterblast Head', NULL, N'MM45', 15)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Blasting - Sandblaster/Safety Equipment (Single Nozzle)    ', N'RM1723', NULL, 16)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Blasting - Sandblaster/Safety Equipment (Double Nozzle)', NULL, NULL, 17)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Blasting - Sandblaster/Safety Equipment (Triple Nozzle)', NULL, NULL, 18)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Blasting - Blast Bully blast wand (Little Bully #38)', NULL, NULL, 19)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Boom Truck - Winch Truck 4WD', NULL, NULL, 20)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Boom Truck -  2 Ton w/ 8 ton knuckle boom', NULL, NULL, 21)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Boom Truck -15 ton', NULL, NULL, 22)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Boom Truck - Peterbilt 375 with 23 ton boom', NULL, NULL, 23)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Butt Fusion Machine (1/2" to 1") ', N'RM1901', NULL, 24)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Butt Fusion Machine (1/2" to 2") ', N'RM1902', NULL, 25)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Butt Fusion Machine (2" to 8") ', N'RM1903', NULL, 26)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Butt Fusion Machine (4" to 12") ', N'RM1904', NULL, 27)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Butt Fusion Machine (6" to 18") ', N'RM1905', NULL, 28)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Butt Fusion Machine (8" to 20") ', N'RM1906', NULL, 29)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Butt Fusion Line Tamer/Straightener', N'RM1907', NULL, 30)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Butt Fusion EF Processor (Electro-fusion Machine)', N'RM1908', NULL, 31)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Butt Fusion Sidewinder (Side or Tee Tap)', N'RM1909', NULL, 32)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Coating - Spray Trailer (Complete)', NULL, N'MM32', 33)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Compactor - Jumping Jack Compactor (to 5000 lbs CF)     ', N'RM0601', NULL, 34)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Compactor - Impact Plate Compactor (to 8000 lbs CF)', N'RM0602', NULL, 35)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Compactor - Air Backfill Tamper (Pogo stick) or equal', N'RM0603', NULL, 36)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Demolition - Sullair Air Breaker/Hammer (up to 35 lbs)     ', N'RM0501', NULL, 37)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Demolition - Sullair Air Breaker/Hammer (36 to 60 lbs)     ', N'RM0502', NULL, 38)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Demolition - Sullair Air Breaker/Hammer (61 to 90 lbs)     ', N'RM0503', NULL, 39)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Demolition - Sullair Rock Drill (up to 30 lbs) includes bits', N'RM0504', NULL, 40)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Demolition - Sullair Rock Drill (31 to 50 lbs) includes bits', N'RM0505', NULL, 41)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Demolition - Concrete Saw (up to 14" hand-held)     ', N'RM0506', NULL, 42)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Demolition - Concrete Saw (up to 16" walk behind)', N'RM0507', NULL, 43)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Demolition - Concrete Saw (18" to 26" walk behind)', N'RM0508', NULL, 44)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Demolition - Wachs Radial Pipe Cutter', N'RM0509', NULL, 45)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Demolition - Mears Longitudinal/Axial Pipe Cutter', N'RM0510', NULL, 46)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Demolition - Hand Lance (high pressure/low volume water)', N'RM0511', NULL, 47)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Demolition - Air Knife', N'RM0512', NULL, 48)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Dozer - Cat D3 low track or equal (up to 17,500 lbs)', N'RM0801', NULL, 49)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Dozer - Cat D4 low track or equal (17,500 to 18,000 lbs)', N'RM0802', NULL, 50)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Dozer - Cat D5 low track or equal (18,001 to 21,000 lbs)', N'RM0803', NULL, 51)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Dozer - Cat D6 low track or equal (30,001 to 55,000 lbs)', N'RM0804', NULL, 52)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Dozer - Cat D4 high track or equal (up to 26,000 lbs)     ', N'RM0805', NULL, 53)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Dozer - Cat D5 high track or equal (26,001 to 30,000 lbs)', N'RM0806', NULL, 54)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Dozer - Cat D6 high track or equal (30,001 to 55,000 lbs)', N'RM0807', NULL, 55)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Dozer - Cat D7 high track or equal (55,001 to 60,000 lbs)', N'RM0808', NULL, 56)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Dozer - Cat D8 or equal (60,001 to 85,000 lbs)', N'RM0809', NULL, 57)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Drilling - Vermeer D80x100 or equal', N'RM1101', NULL, 58)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Drilling - Vermeer D50x100 or equal', N'RM1102', NULL, 59)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Drilling - Vermeer D24x40 or equal', N'RM1103', N'MM41', 60)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Drilling - Vermeer D16x20 or equal', N'RM1104', NULL, 61)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Drilling - Vermeer D7x11 or equal', N'RM1105', NULL, 62)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Drilling - Mud Mixing System/Directional Bore Tanker Truck', NULL, N'MM20', 63)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Excavator - Cat 416 Backhoe or equal*     ', N'RM0302', N'MM08', 64)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Excavator - Cat 416 Backhoe extend a hoe or equal*', N'RM0303', N'MM08', 65)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Excavator - Cat 301 or equal (up to 4,500 lbs)', N'RM0304', NULL, 66)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Excavator Cat 302 or equal (4,501 to 7,000 lbs)', N'RM0305', NULL, 67)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Excavator Cat 303 or equal (7,001 to 10,000 lbs)', N'RM0306', NULL, 68)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Excavator Cat 305 or equal (10,001 to 15,000 lbs)', N'RM0307', NULL, 69)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Excavator Cat 307/308 or equal (15,001 to 19,000 lbs)     22', N'RM0308', N'MM14', 70)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Excavator Cat 312 or equal (19,001 to 29,000 lbs)     ', N'RM0309', N'MM15', 71)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Excavator Cat 315 or equal (29,001 to 39,000 lbs)     ', N'RM0310', N'MM16', 72)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Excavator Cat 320 or equal  (39,001 to 53,000 lbs)     ', N'RM0311', N'MM07', 73)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Excavator Cat 325 or equal  (53,001 to 65,000 lbs)     ', N'RM0312', N'MM17', 74)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Excavator Cat 330 or equal  (65,001 to 75,000 lbs)     ', N'RM0313', NULL, 75)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Excavator - Wheel Excavator (Up to 40,000 lbs)', N'RM0314', NULL, 76)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Excavator - Wheel Excavator (40,001 to 45,000 lbs)', N'RM0315', NULL, 77)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'W/Hammer Excavator - Cat 416 Backhoe or equal*', N'RHM0302', N'MHM08', 78)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'W/Hammer Excavator - Cat 416 Backhoe extend a hoe or equal*', N'RHM0303', N'MHM08', 79)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'W/Hammer Excavator - Cat 301 or equal (up to 4,500 lbs)', N'RHM0304', NULL, 80)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'W/Hammer Excavator Cat 302 or equal (4,501 to 7,000 lbs)', N'RHM0305', NULL, 81)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'W/Hammer Excavator Cat 303 or equal (7,001 to 10,000 lbs)', N'RHM0306', NULL, 82)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'W/Hammer Excavator Cat 305 or equal (10,001 to 15,000 lbs)', N'RHM0307', NULL, 83)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'W/Hammer Excavator Cat 307/308 or equal (15,001 to 19,000 lbs)', N'RHM0308', N'MHM14', 84)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'W/Hammer Excavator Cat 312 or equal (19,001 to 29,000 lbs)', N'RHM0309', N'MHM15', 85)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'W/Hammer Excavator Cat 315 or equal (29,001 to 39,000 lbs)     ', N'RHM0310', N'MHM16', 86)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'W/Hammer Excavator Cat 320 or equal  (39,001 to 53,000 lbs)     ', N'RHM0311', N'MHM07', 87)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'W/Hammer Excavator Cat 325 or equal  (53,001 to 65,000 lbs)', N'RHM0312', N'MHM17', 88)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'W/Hammer Excavator Cat 330 or equal  (65,001 to 75,000 lbs)', N'RHM0313', NULL, 89)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'W/Hammer Excavator - Wheel Excavator (Up to 40,000 lbs)', N'RHM0314', NULL, 90)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'W/Hammer Excavator - Wheel Excavator (40,001 to 45,000 lbs)', N'RHM0315', NULL, 91)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Excavator - Vacuum Truck w/operator     ', N'RM0401', N'MM42', 92)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Excavator - Vacuum Trailer (for pot holing only)     ', N'RM0404', N'MM40', 93)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Excavator - Vacuum Trailer w/casing flush attachment ', NULL, NULL, 94)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Generator (up to 8000 watt)     ', N'RM1301', NULL, 95)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Generator (8000 to 10,000 watt)     ', N'RM1302', NULL, 96)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Generator (10,001 to 15000 watt)', N'RM1303', NULL, 97)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Generator (15001 to 20,000 watt)', N'RM1304', NULL, 98)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Generator (20,001 to 25,000 watt)     ', N'RM1305', NULL, 99)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Loader - Cat IT14 or equal (up to 20,000 lbs) ', N'RM1009', NULL, 100)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Loader - Cat IT28 or equal (20,001 to 28,000 lbs)', N'RM1010', NULL, 101)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Loader - Cat IT38 or equal (28,001 to 36,000 lbs)', N'RM1011', NULL, 102)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Misc - 200 to 500 Gal. Water Tank - Skid Mounted w/pump     ', N'RM1711', NULL, 103)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Misc - Air Lifting Bag w/manifold (1.5 to 70 ton capacity)     ', N'RM1704', NULL, 104)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Misc - Bale Chopper/Mulcher     ', N'RM1705', NULL, 105)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Misc - Chainsaw     ', N'RM1706', NULL, 106)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Misc - Hardwood Mats (each per day)     ', N'RM1710', NULL, 107)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Misc - Hydraulic Planer/Mill     MA', N'RM1701', NULL, 108)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Misc - Hydraulic Power Auger Motor w/8" - 16" auger ', N'RM1702', NULL, 109)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Misc - Light Tower 6000 Watt     ', N'RM1306', NULL, 110)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Misc - Oxygen/Acetylene Cutting Torch     ', N'RM1709', NULL, 111)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Misc - Pipe Jeep (includes spring)     ', N'RM1703', NULL, 112)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Misc - Pipe Roller (2" to 12")', NULL, NULL, 113)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Misc - Welder (200 amp)     ', N'RM1707', NULL, 114)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Plow - Cat D6 high track w/Plow or equal', N'RM0901', N'MM47', 115)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Plow - Komatsu D65 EX-Plow or equal', N'RM0902', N'MM24', 116)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Plow - Cat D7 high track w/plow or equal', N'RM0903', N'MM43', 117)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Plow - Cat D8 w/Plow or equal', N'RM0905', N'MM44', 118)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Shoring - Speed Shore Hydraulic Jacks (up to 88")     ', N'RM1501', NULL, 119)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Shoring - Fin Form Sheet (4'' x 8'')     ', N'RM1502', NULL, 120)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Shoring - Speed Shore Pump w/Release Tool & Hook    ', N'RM1503', NULL, 121)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Shoring - Steel Trench Box (up to 8'' x 10'')     ', N'RM1504', NULL, 122)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Shoring - Steel Trench Box (8'' x 12'' to 8'' x 16'')     ', N'RM1505', NULL, 123)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Shoring - Manhole Box Steel (up to 4''x 10''x10'')     ', N'RM1506', NULL, 124)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Shoring - Manhole Box Steel (5''x10''x10'' to 8''x10''x 10'')     ', N'RM1507', NULL, 125)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Shoring - Aluminum Shield/Trench Box - (up to 6'' x 8'')     ', N'RM1508', NULL, 126)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Shoring - Aluminum Shield/Trench Box - (6''x10'' to 8''x10'' )     ', N'RM1509', NULL, 127)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Shoring - Aluminum End Panel Kit - (up to 62" W & 10'' L)     ', N'RM1510', NULL, 128)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Shoring - Aluminum End Panel Kit - (63"-71" W up to 10'' L)     ', N'RM1511', NULL, 129)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Sideboom - Cat 583 or equal (up to 100,000 lbs)', NULL, NULL, 130)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Sideboom - Cat 572 or equal (61,300 to 97,999 lbs)', NULL, NULL, 131)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Sideboom - Cat 571 or equal (50,300 to 61,299 lbs)', NULL, NULL, 132)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Sideboom - Cat 561 or equal (35,000 to 50,299 lbs)', NULL, NULL, 133)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Sideboom - Cat 541 or equal (up to 34,999 lbs)', NULL, NULL, 134)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Skid Steer Cat 246C or equal (capacity up to 2150 lbs)', N'RM1001', NULL, 135)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Skid Steer Cat 256C or equal (cap 2151 to 2350 lbs)     ', N'RM1002', NULL, 136)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Skid Steer Cat 262C or equal (cap 2351 to 2700 lbs)     ', N'RM1003', NULL, 137)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Skid Steer Cat 272C or equal (cap 2701 to 3250 lbs)', N'RM1004', NULL, 138)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Telehandler Cat TH255 or equal (capacity up to 5500 lbs)     ', N'RM1005', NULL, 139)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Telehandler Cat TL642 or equal (cap 5501 to 6500 lbs)     ', N'RM1006', NULL, 140)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Telehandler w/stabilizers (cap 5501 to 6500 lbs)', N'RM1007', NULL, 141)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Telehandler w/stabilizers (cap 5501 to 9000 lbs) ', N'RM1008', NULL, 142)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Tractor - Farm Tractor ', N'RM0301', NULL, 143)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Tractor - Farm Tractor (up to 40 HP)', N'RM1013', NULL, 144)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Tractor - Farm Tractor (41 to 90 HP)     ', N'RM1014', N'MM25', 145)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'*Hydraulic Hammer Equipped, 2x the machine rate.  ', NULL, NULL, 146)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Traffic Control - Flag Control', N'RM1601', NULL, 147)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Traffic Control - Shoulder Closure', N'RM1602', NULL, 148)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Traffic Control - Lane Closure', N'RM1603', NULL, 149)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Traffic Control - Water Filled Barrier (per unit)     ', N'RM1604', NULL, 150)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Traffic Control - Concrete Barrier (per unit)', N'RM1605', NULL, 151)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Traffic Control - Arrow Board', N'RM1606', NULL, 152)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Traffic Control - Portable Temporary Traffic Signal', N'RM1607', NULL, 153)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Traffic Control - Crash Attenuator - Trailer ', N'RM1608', NULL, 154)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Traffic Control - Crash Attenuator - Truck', N'RM1609', N'MM39', 155)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Trailer - Tag Trailer (up to 9 ton)', N'RM1910', N'MM36', 156)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Trailer - Tag Trailer (10 ton to 20 ton)     ', N'RM0210', N'MM35', 157)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Trailer - Lowboy Trailer     ', N'RM0211', N'MM26', 158)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Trailer - 40''  Flatbed trailer or equal', NULL, N'MM04', 159)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Trailer - 40'' Van/Tool Trailer', NULL, N'MM05', 160)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Trailer - 500 Gallon Water Trailer     ', N'RM0206', NULL, 161)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Trailer - 7500 Gallon Water Trailer', NULL, NULL, 162)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Trailer - Casing Tool Trailer     ', N'RM2013', NULL, 163)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Trailer - Tool Trailer     ', N'RM0214', N'MM37', 164)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Trailer - Office Trailer', NULL, NULL, 165)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Trailer - Coke Breeze Trailer', NULL, N'MM18', 166)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Trailer - Pipe Trailer (40 foot pipe/pole trailer)', NULL, NULL, 167)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Trailer - Mulch Wagon     ', N'RM1705', NULL, 168)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Trailer - Reel Trailer single place', NULL, N'MM31', 169)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Trailer - Reel Trailer 2 to 4 place', NULL, N'MM30', 170)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Trencher - Vermeer RTX 450 trencher or equal     ', N'RM0912', NULL, 171)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Trencher - Vermeer RTX 650 trencher or equal', N'RM0913', NULL, 172)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Trencher - Vermeer RTX 950 trencher or equal', N'RM0914', NULL, 173)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Trencher - Vermeer RTX 1250 trencher or equal', N'RM0915', N'MM48', 174)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Trencher - Mears Horizontal Bellhole Trencher', NULL, N'MM27', 175)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Trench Plate - Steel (1" x 4'' x 10'' - approx 1635 lbs)     ', N'RM1512', NULL, 176)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Trench Plate - Steel (1" x 6'' x 12'' - approx 2940 lbs)     ', N'RM1513', NULL, 177)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Trench Plate - Steel (1" x 8'' x 10'' - approx 3270 lbs)     ', N'RM1514', NULL, 178)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Trench Plate - Steel (1" x 8'' x 12'' - approx 3925 lbs)     ', N'RM1515', NULL, 179)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Trench Plate - Steel (1" x 8'' x 15'' - approx 4875 lbs)     ', N'RM1516', NULL, 180)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Trench Plate - Steel (1 1/2" x 6'' x 12'' - approx 4410 lbs)     ', N'RM1517', NULL, 181)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Trench Plate - Steel (1 1/2" x 8'' x 15'' - approx 7350 lbs)     ', N'RM1518', NULL, 182)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Truck - Mechanics Truck', NULL, N'MM28', 183)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Truck - Welding Rig', NULL, NULL, 184)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Truck - Pickup', NULL, N'MM29', 185)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Truck - Tech Truck     ', N'RM0107', N'MM22', 186)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Truck - 1 Ton Truck     ', N'RM0102', N'MM01', 187)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Truck - 2 Ton Truck     ', N'RM0103', N'MM02', 188)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Truck - Dump Truck Single Axle     ', N'RM0104', N'MM21', 189)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Truck - Dump Truck Tandem Axle     ', N'RM0105', NULL, 190)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Truck - Tractor/Semi     ', N'RM0108', N'MM38', 191)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Truck - 2 Ton Water Tanker     ', N'RM0106', NULL, 192)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Water Pump ( up to 2")     ', N'RM1401', NULL, 193)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Water Pump (3")     ', N'RM1402', NULL, 194)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Water Pump (4")     ', N'RM1404', NULL, 195)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Water Pump (5")', N'RM1405', NULL, 196)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Water Pump (6")     ', N'RM1406', NULL, 197)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Winch - Cat D4 high track w/EX Winch or equal', N'RM0806', NULL, 198)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Winch - Cat D5 high track w/EX Winch or equal', N'RM0907', N'MM10', 199)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Winch - Cat D6 high track w/EX Winch or equal', N'RM0908', N'MM11', 200)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Winch - Komatsu D65 w/EX-Winch or equal', N'RM0909', N'MM46', 201)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Winch - Cat D7 high track w/EX Winch or equal', N'RM0910', N'MM12', 202)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Winch - Cat D8 w/EX Winch or equal', N'RM0911', N'MM13', 203)
GO
INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] ([EQUIPMENT_DESCRIPTION], [EQUIPMENT_CODE], [OWNED_BILLING_CODES], [EQUIPMENT_BILLING_CODE_ID]) VALUES (N'Raptor Automated UT Scanner', NULL, NULL, 204)
GO
SET IDENTITY_INSERT [dbo].[ML_EQUIPMENT_BILLING_CODE_T] OFF
GO
SET IDENTITY_INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ON 
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (127, N'CS', N'Corrosion Specialist')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (129, N'CPS', N'CP Specialist/NACE CP 4')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (130, N'SCT
', N'Sr Corrosion TechNACE CP3')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (131, N'CTECH
', N'Corrosion Tech/NACE CP2')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (132, N'CTEST', N'Corrosion Tester/NACE CP1')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (133, N'ST', N'Senior Technician')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (134, N'T', N'Technician')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (135, N'TA', N'Technical Assistant')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (136, N'NST', N'NDT Sr Tech ASNT III')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (137, N'NSTOT
', N'NDT Sr Tech ASNT III (OT)')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (138, N'DEI
', N'DE/NDT Technician 1')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (139, N'DEIOT
', N'DE/NDT Technician 1 OT')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (140, N'DEII
', N'DE/NDT Technician 2 ')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (141, N'DEIIOT
', N'DE/NDT Technician 2 OT')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (142, N'DEIII
', N'DE/NDT Technician 3')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (143, N'DEIIIOT', N'DE/NDT Technician 3 OT')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (144, N'DEIIIIOT
', N'DE/NDT Technician 4 OT')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (145, N'CE
', N'Chief Engineer (PE)')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (146, N'SE
', N'Senior  Engineer')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (147, N'E
', N'Engineer')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (148, N'DAS
', N'DA Specialist')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (149, N'CAD
', N'CAD w/Operator')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (150, N'VPI
', N'VP Integrity ')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (151, N'DI
', N'Director PI/Engineering')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (152, N'PCT
', N'Quality Assur Inspector')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (153, N'QAI
', N'Quality Assurance Inspector')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (154, N'DP
', N'Data Processing')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (155, N'CT
', N'Clerical Tech')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (156, N'PCC
', N'Project Coordinator Const')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (157, N'PCCOT
', N'Project Coord Const OT')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (158, N'SU
', N'Superintendent')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (159, N'SOT
', N'Superintendent OT')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (160, N'F
', N'Foreman')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (161, N'FOT
', N'Foreman OT')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (162, N'M
', N'Mechanic')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (163, N'MOT
', N'Mechanic OT')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (164, N'OII
', N'Operator II')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (165, N'OIIOT
', N'Operator II OT')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (166, N'OI
', N'Operator I')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (167, N'OIOT
', N'Operator I OT')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (168, N'S
', N'Sprayer')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (169, N'SOT
', N'Sprayer OT')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (170, N'TD
', N'Truck Driver/CDL')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (171, N'TDOT
', N'Truck Driver/CDL OT')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (172, N'L
', N'Laborer')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (173, N'LOT
', N'Laborer OT')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (174, N'WR
', N'Welder w/Rig')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (175, N'WROT
', N'Welder w/Rig OT')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (176, N'CC
', N'Construction Clerk')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (177, N'CCOT
', N'Construction Clerk OT')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (178, N'SP
', N'Safety Professional ')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (179, N'SPOT
', N'Safety Professional OT')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (180, N'BH
', N'BELL HOLE TECHNICIAN     ')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (181, N'BHOT
', N'BELL HOLE TECHNICIAN   OT')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (182, N'ER
', N'EXPERT WITNESS/REGULATORY')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (183, N'MI
', N'MANAGER INSPECTION SRVS  ')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (184, N'TPD
', N'TECH PER DIEM ')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (185, N'CPD
', N'CONSTRUCTION PER DIEM ')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (186, N'AD
', N'ADMINISTRATION NON BILL')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (187, N'OTH
', N'OTHER')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (188, N'MNDT
', N'MANAGER NDT SERVICES')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (189, N'CM
', N'CONSTRUCTION MANAGER')
GO
INSERT [dbo].[ML_LABOR_BILLING_CODE_T] ([LABOR_BILLING_CODE_ID], [LABOR_BILLING_CODE], [LABOR_BILLING_DESCRIPTION]) VALUES (190, N'DEIIII
', N'DE/NDT Technician 4')
GO
SET IDENTITY_INSERT [dbo].[ML_LABOR_BILLING_CODE_T] OFF
GO
INSERT [dbo].[ML_SURVEY_TYPE_T] ([Survey_Type_Id], [Survey_Type], [IsActiveSurveyType]) VALUES (1, N'ECDA', 1)
GO
INSERT [dbo].[ML_SURVEY_TYPE_T] ([Survey_Type_Id], [Survey_Type], [IsActiveSurveyType]) VALUES (2, N'CIS', 1)
GO
INSERT [dbo].[ML_SURVEY_TYPE_T] ([Survey_Type_Id], [Survey_Type], [IsActiveSurveyType]) VALUES (3, N'Interruption', 1)
GO
INSERT [dbo].[ML_SURVEY_TYPE_T] ([Survey_Type_Id], [Survey_Type], [IsActiveSurveyType]) VALUES (4, N'PCM', 1)
GO
INSERT [dbo].[ML_SURVEY_TYPE_T] ([Survey_Type_Id], [Survey_Type], [IsActiveSurveyType]) VALUES (5, N'DCVG', 1)
GO
INSERT [dbo].[ML_SURVEY_TYPE_T] ([Survey_Type_Id], [Survey_Type], [IsActiveSurveyType]) VALUES (6, N'ACVG', 1)
GO
INSERT [dbo].[ML_SURVEY_TYPE_T] ([Survey_Type_Id], [Survey_Type], [IsActiveSurveyType]) VALUES (7, N'Soil Resistivity', 1)
GO
INSERT [dbo].[ML_SURVEY_TYPE_T] ([Survey_Type_Id], [Survey_Type], [IsActiveSurveyType]) VALUES (8, N'Drilling', 1)
GO
INSERT [dbo].[ML_SURVEY_TYPE_T] ([Survey_Type_Id], [Survey_Type], [IsActiveSurveyType]) VALUES (9, N'Restoration', 1)
GO
INSERT [dbo].[ML_SURVEY_TYPE_T] ([Survey_Type_Id], [Survey_Type], [IsActiveSurveyType]) VALUES (10, N'Casing', 1)
GO
INSERT [dbo].[ML_SURVEY_TYPE_T] ([Survey_Type_Id], [Survey_Type], [IsActiveSurveyType]) VALUES (11, N'Mark & Locate', 1)
GO
INSERT [dbo].[ML_SURVEY_TYPE_T] ([Survey_Type_Id], [Survey_Type], [IsActiveSurveyType]) VALUES (12, N'Depth of Cover', 1)
GO
INSERT [dbo].[ML_SURVEY_TYPE_T] ([Survey_Type_Id], [Survey_Type], [IsActiveSurveyType]) VALUES (13, N'Atmospheric', 1)
GO
INSERT [dbo].[ML_SURVEY_TYPE_T] ([Survey_Type_Id], [Survey_Type], [IsActiveSurveyType]) VALUES (14, N'Water Pack', 1)
GO
INSERT [dbo].[ML_SURVEY_TYPE_T] ([Survey_Type_Id], [Survey_Type], [IsActiveSurveyType]) VALUES (15, N'SPECIAL PROJECTS', 1)
GO
INSERT [dbo].[ML_SURVEY_TYPE_T] ([Survey_Type_Id], [Survey_Type], [IsActiveSurveyType]) VALUES (16, N'Coupons', 1)
GO
INSERT [dbo].[ML_SURVEY_TYPE_T] ([Survey_Type_Id], [Survey_Type], [IsActiveSurveyType]) VALUES (17, N'Pearson', 1)
GO
INSERT [dbo].[ML_SURVEY_TYPE_T] ([Survey_Type_Id], [Survey_Type], [IsActiveSurveyType]) VALUES (18, N'FL Crossings', 1)
GO
INSERT [dbo].[ML_SURVEY_TYPE_T] ([Survey_Type_Id], [Survey_Type], [IsActiveSurveyType]) VALUES (19, N'Wenner 4-Pin', 1)
GO
INSERT [dbo].[ML_SURVEY_TYPE_T] ([Survey_Type_Id], [Survey_Type], [IsActiveSurveyType]) VALUES (20, N'Probe', 1)
GO
INSERT [dbo].[ML_SURVEY_TYPE_T] ([Survey_Type_Id], [Survey_Type], [IsActiveSurveyType]) VALUES (21, N'Annual', 1)
GO
SET IDENTITY_INSERT [dbo].[ML_TASK_T] ON 
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'Holiday', 1)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'Vacation', 2)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'Documentation/Review', 3)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'Equipment', 4)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'Field - Senior Technician', 5)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'Field - Technical Assistant', 6)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'Field - Technician', 7)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'Field Visit', 8)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'Field Work', 9)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'Inspection', 10)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'Meetings', 11)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'Non-Safety Training', 12)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'Office - Non-billable', 13)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'Omnimetrix', 14)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'OQ Evaluations', 15)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'Personal Time Off', 16)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'Planning/Schedule', 17)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'Process Data', 18)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'QC Data Audit', 19)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'QC Data Review', 20)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'QC Data-Casings', 21)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'QC Data-CIS', 22)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'QC Data-FDB', 23)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'QC Data-GPS-ACCIS-ACVG', 24)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'QC Data-GPS-DCVG-SOIL', 25)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'QC Data-GPS-PCM', 26)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'QC Data-Matching', 27)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'QC Field Audit', 28)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'Sick Day', 29)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'Safety Training', 30)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'Training (Field)', 31)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'Training (Office)', 32)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (911, N'Travel', 33)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'Holiday', 34)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'Vacation', 35)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'Documentation/Review', 36)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'Equipment', 37)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'Field - Senior Technician', 38)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'Field - Technical Assistant', 39)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'Field - Technician', 40)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'Field Visit', 41)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'Field Work', 42)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'Inspection', 43)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'Meetings', 44)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'Non-Safety Training', 45)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'Office - Non-billable', 46)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'Omnimetrix', 47)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'OQ Evaluations', 48)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'Personal Time Off', 49)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'Planning/Schedule', 50)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'Process Data', 51)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'QC Data Audit', 52)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'QC Data Review', 53)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'QC Data-Casings', 54)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'QC Data-CIS', 55)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'QC Data-FDB', 56)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'QC Data-GPS-ACCIS-ACVG', 57)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'QC Data-GPS-DCVG-SOIL', 58)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'QC Data-GPS-PCM', 59)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'QC Data-Matching', 60)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'QC Field Audit', 61)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'Sick Day', 62)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'Safety Training', 63)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'Training (Field)', 64)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'Training (Office)', 65)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (912, N'Travel', 66)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'Holiday', 67)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'Vacation', 68)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'Documentation/Review', 69)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'Equipment', 70)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'Field - Senior Technician', 71)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'Field - Technical Assistant', 72)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'Field - Technician', 73)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'Field Visit', 74)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'Field Work', 75)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'Inspection', 76)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'Meetings', 77)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'Non-Safety Training', 78)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'Office - Non-billable', 79)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'Omnimetrix', 80)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'OQ Evaluations', 81)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'Personal Time Off', 82)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'Planning/Schedule', 83)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'Process Data', 84)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'QC Data Audit', 85)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'QC Data Review', 86)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'QC Data-Casings', 87)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'QC Data-CIS', 88)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'QC Data-FDB', 89)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'QC Data-GPS-ACCIS-ACVG', 90)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'QC Data-GPS-DCVG-SOIL', 91)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'QC Data-GPS-PCM', 92)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'QC Data-Matching', 93)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'QC Field Audit', 94)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'Sick Day', 95)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'Safety Training', 96)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'Training (Field)', 97)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'Training (Office)', 98)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (913, N'Travel', 99)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'Holiday', 100)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'Vacation', 101)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'Documentation/Review', 102)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'Equipment', 103)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'Field - Senior Technician', 104)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'Field - Technical Assistant', 105)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'Field - Technician', 106)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'Field Visit', 107)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'Field Work', 108)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'Inspection', 109)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'Meetings', 110)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'Non-Safety Training', 111)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'Office - Non-billable', 112)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'Omnimetrix', 113)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'OQ Evaluations', 114)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'Personal Time Off', 115)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'Planning/Schedule', 116)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'Process Data', 117)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'QC Data Audit', 118)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'QC Data Review', 119)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'QC Data-Casings', 120)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'QC Data-CIS', 121)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'QC Data-FDB', 122)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'QC Data-GPS-ACCIS-ACVG', 123)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'QC Data-GPS-DCVG-SOIL', 124)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'QC Data-GPS-PCM', 125)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'QC Data-Matching', 126)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'QC Field Audit', 127)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'Sick Day', 128)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'Safety Training', 129)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'Training (Field)', 130)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'Training (Office)', 131)
GO
INSERT [dbo].[ML_TASK_T] ([Company], [Task], [TASK_ID]) VALUES (914, N'Travel', 132)
GO
SET IDENTITY_INSERT [dbo].[ML_TASK_T] OFF
GO
